INSERT INTO `CARTA` VALUES ('Captain''s Parrot','Minion','Neutral','Promo','Epic','Beast','2','1','1','Battlecry: Put a random Pirate from your deck into your hand.','0');
INSERT INTO `CARTA` VALUES ('Elite Tauren Chieftain','Minion','Neutral','Promo','Legendary',NULL,'5','5','5','Battlecry: Give both players the power to ROCK! (with a Power Chord card)','0');
INSERT INTO `CARTA` VALUES ('Gelbin Mekkatorque','Minion','Neutral','Promo','Legendary',NULL,'6','6','6','Battlecry: Summon an AWESOME invention','0');
INSERT INTO `CARTA` VALUES ('Old Murk-Eye','Minion','Neutral','Promo','Legendary','Murloc','4','2','4','Charge. Has +1 Attack for each other Murloc on the battlefield','0');
INSERT INTO `CARTA` VALUES ('Acidic Swamp Ooze','Minion','Neutral','Basic','Basic',NULL,'2','3','2','Battlecry: Destroy your opponent''s weapon','2');
INSERT INTO `CARTA` VALUES ('Archmage','Minion','Neutral','Basic','Basic',NULL,'6','4','7','Spell Damage +1','2');
INSERT INTO `CARTA` VALUES ('Bloodfen Raptor','Minion','Neutral','Basic','Basic','Beast','2','3','2',NULL,'2');
INSERT INTO `CARTA` VALUES ('Bluegill Warrior','Minion','Neutral','Basic','Basic','Murloc','2','2','1','Charge','2');
INSERT INTO `CARTA` VALUES ('Booty Bay Bodyguard','Minion','Neutral','Basic','Basic',NULL,'5','5','4','Taunt','2');
INSERT INTO `CARTA` VALUES ('Boulderfist Ogre','Minion','Neutral','Basic','Basic',NULL,'6','6','7',NULL,'2');
INSERT INTO `CARTA` VALUES ('Chillwind Yeti','Minion','Neutral','Basic','Basic',NULL,'4','4','5',NULL,'2');
INSERT INTO `CARTA` VALUES ('Core Hound','Minion','Neutral','Basic','Basic','Beast','7','9','5',NULL,'2');
INSERT INTO `CARTA` VALUES ('Dalaran Mage','Minion','Neutral','Basic','Basic',NULL,'3','1','4','Spell Damage +1','2');
INSERT INTO `CARTA` VALUES ('Darkscale Healer','Minion','Neutral','Basic','Basic',NULL,'5','4','5','Battlecry: Restore 2 Health to all friendly characters','2');
INSERT INTO `CARTA` VALUES ('Dragonling Mechanic','Minion','Neutral','Basic','Basic',NULL,'4','2','4','Battlecry: Summon a 2/1 Mechanical Dragonling','2');
INSERT INTO `CARTA` VALUES ('Elven Archer','Minion','Neutral','Basic','Basic',NULL,'1','1','1','Battlecry: Deal 1 damage','2');
INSERT INTO `CARTA` VALUES ('Frostwolf Grunt','Minion','Neutral','Basic','Basic',NULL,'2','2','2','Taunt','2');
INSERT INTO `CARTA` VALUES ('Frostwolf Warlord','Minion','Neutral','Basic','Basic',NULL,'5','4','4','Battlecry: Gain +1/+1 for each other friendly minion on the battlefield','2');
INSERT INTO `CARTA` VALUES ('Gnomish Inventor','Minion','Neutral','Basic','Basic',NULL,'4','2','4','Battlecry: Draw a card','2');
INSERT INTO `CARTA` VALUES ('Goldshire Footman','Minion','Neutral','Basic','Basic',NULL,'1','1','2','Taunt','2');
INSERT INTO `CARTA` VALUES ('Grimscale Oracle','Minion','Neutral','Basic','Basic','Murloc','1','1','1','ALL other Murlocs have +1 Attack','2');
INSERT INTO `CARTA` VALUES ('Gurubashi Berserker','Minion','Neutral','Basic','Basic',NULL,'5','2','7','Whenever this minion takes damage, gain +3 attack','2');
INSERT INTO `CARTA` VALUES ('Ironforge Rifleman','Minion','Neutral','Basic','Basic',NULL,'3','2','2','Battlecry: Deal 1 damage','2');
INSERT INTO `CARTA` VALUES ('Ironfur Grizzly','Minion','Neutral','Basic','Basic','Beast','3','3','3','Taunt','2');
INSERT INTO `CARTA` VALUES ('Kobold Geomancer','Minion','Neutral','Basic','Basic',NULL,'2','2','2','Spell Damage +1','2');
INSERT INTO `CARTA` VALUES ('Lord of the Arena','Minion','Neutral','Basic','Basic',NULL,'6','6','5','Taunt','2');
INSERT INTO `CARTA` VALUES ('Magma Rager','Minion','Neutral','Basic','Basic',NULL,'3','5','1',NULL,'2');
INSERT INTO `CARTA` VALUES ('Murloc Raider','Minion','Neutral','Basic','Basic','Murloc','1','2','1',NULL,'2');
INSERT INTO `CARTA` VALUES ('Murloc Tidehunter','Minion','Neutral','Basic','Basic','Murloc','2','2','1','Battlecry: Summon a 1/1 Murloc Scout','2');
INSERT INTO `CARTA` VALUES ('Nightblade','Minion','Neutral','Basic','Basic',NULL,'5','4','4','Battlecry: Deal 3 damage to the enemy hero','2');
INSERT INTO `CARTA` VALUES ('Novice Engineer','Minion','Neutral','Basic','Basic',NULL,'2','1','1','Battlecry: Draw a card','2');
INSERT INTO `CARTA` VALUES ('Oasis Snapjaw','Minion','Neutral','Basic','Basic','Beast','4','2','7',NULL,'2');
INSERT INTO `CARTA` VALUES ('Ogre Magi','Minion','Neutral','Basic','Basic',NULL,'4','4','4','Spell Damage +1','2');
INSERT INTO `CARTA` VALUES ('Raid Leader','Minion','Neutral','Basic','Basic',NULL,'3','2','2','Your other minions have +1 Attack','2');
INSERT INTO `CARTA` VALUES ('Razorfen Hunter','Minion','Neutral','Basic','Basic',NULL,'3','2','3','Battlecry: Summon a 1/1 Boar','2');
INSERT INTO `CARTA` VALUES ('Reckless Rocketeer','Minion','Neutral','Basic','Basic',NULL,'6','5','2','Charge','2');
INSERT INTO `CARTA` VALUES ('River Crocolisk','Minion','Neutral','Basic','Basic','Beast','2','2','3',NULL,'2');
INSERT INTO `CARTA` VALUES ('Sen''jin Shieldmasta','Minion','Neutral','Basic','Basic',NULL,'4','3','5','Taunt','2');
INSERT INTO `CARTA` VALUES ('Shattered Sun Cleric','Minion','Neutral','Basic','Basic',NULL,'3','3','2','Battlecry: Give a friendly minion +1/+1','2');
INSERT INTO `CARTA` VALUES ('Silverback Patriarch','Minion','Neutral','Basic','Basic','Beast','3','1','4','Taunt','2');
INSERT INTO `CARTA` VALUES ('Stonetusk Boar','Minion','Neutral','Basic','Basic','Beast','1','1','1','Charge','2');
INSERT INTO `CARTA` VALUES ('Stormpike Commando','Minion','Neutral','Basic','Basic',NULL,'5','4','2','Battlecry: Deal 2 damage','2');
INSERT INTO `CARTA` VALUES ('Stormwind Champion','Minion','Neutral','Basic','Basic',NULL,'7','6','6','Your other minions have +1/+1','2');
INSERT INTO `CARTA` VALUES ('Stormwind Knight','Minion','Neutral','Basic','Basic',NULL,'4','2','5','Charge','2');
INSERT INTO `CARTA` VALUES ('Voodoo Doctor','Minion','Neutral','Basic','Basic',NULL,'1','2','1','Battlecry: Restore 2 Health','2');
INSERT INTO `CARTA` VALUES ('War Golem','Minion','Neutral','Basic','Basic',NULL,'7','7','7',NULL,'2');
INSERT INTO `CARTA` VALUES ('Wolfrider','Minion','Neutral','Basic','Basic',NULL,'3','3','1','Charge','2');
INSERT INTO `CARTA` VALUES ('Claw','Spell','Druid','Basic','Basic',NULL,'1',NULL,NULL,'Give your hero +2 Attack this turn and +2 Armor','2');
INSERT INTO `CARTA` VALUES ('Healing Touch','Spell','Druid','Basic','Basic',NULL,'3',NULL,NULL,'Restore 8 Health','2');
INSERT INTO `CARTA` VALUES ('Innervate','Spell','Druid','Basic','Basic',NULL,'0',NULL,NULL,'Gain 2 Mana Crystals this turn only','2');
INSERT INTO `CARTA` VALUES ('Ironbark Protector','Minion','Druid','Basic','Basic',NULL,'8','8','8','Taunt','2');
INSERT INTO `CARTA` VALUES ('Mark of the Wild','Spell','Druid','Basic','Basic',NULL,'2',NULL,NULL,'Give a minion Taunt and +2/+2 (+2 Attack/+2 Health)','2');
INSERT INTO `CARTA` VALUES ('Moonfire','Spell','Druid','Basic','Basic',NULL,'0',NULL,NULL,'Deal 1 damage','2');
INSERT INTO `CARTA` VALUES ('Savage Roar','Spell','Druid','Basic','Basic',NULL,'3',NULL,NULL,'Give your characters +2 Attack this turn','2');
INSERT INTO `CARTA` VALUES ('Starfire','Spell','Druid','Basic','Basic',NULL,'6',NULL,NULL,'Deal 5 damage. Draw a card','2');
INSERT INTO `CARTA` VALUES ('Swipe','Spell','Druid','Basic','Basic',NULL,'4',NULL,NULL,'Deal 4 damage to an enemy and 1 damage to all other enemies','2');
INSERT INTO `CARTA` VALUES ('Wild Growth','Spell','Druid','Basic','Basic',NULL,'2',NULL,NULL,'Gain an empty Mana Crystal','2');
INSERT INTO `CARTA` VALUES ('Animal Companion','Spell','Hunter','Basic','Basic',NULL,'3',NULL,NULL,'Summon a random Beast Companion','2');
INSERT INTO `CARTA` VALUES ('Arcane Shot','Spell','Hunter','Basic','Basic',NULL,'1',NULL,NULL,'Deal 2 damage','2');
INSERT INTO `CARTA` VALUES ('Houndmaster','Minion','Hunter','Basic','Basic',NULL,'4',NULL,NULL,'Battlecry: Give a friendly Beast +2/+2 and Taunt','2');
INSERT INTO `CARTA` VALUES ('Hunter''s Mark','Spell','Hunter','Basic','Basic',NULL,'0',NULL,NULL,'Change a minion''s health to 1','2');
INSERT INTO `CARTA` VALUES ('Kill Command','Spell','Hunter','Basic','Basic',NULL,'3',NULL,NULL,'Deal 3 damage. If you control a Beast, deal 5 damage instead','2');
INSERT INTO `CARTA` VALUES ('Multi-Shot','Spell','Hunter','Basic','Basic',NULL,'4',NULL,NULL,'Deal 3 damage to two random enemy minions','2');
INSERT INTO `CARTA` VALUES ('Starving Buzzard','Minion','Hunter','Basic','Basic','Beast','5','3','2','Whenever you summon a Beast, draw a card','2');
INSERT INTO `CARTA` VALUES ('Timber Wolf','Minion','Hunter','Basic','Basic','Beast','1','1','1','Your other Beasts have +1 Attack','2');
INSERT INTO `CARTA` VALUES ('Tracking','Spell','Hunter','Basic','Basic',NULL,'1',NULL,NULL,'Look at the top three cards of your deck. Draw one and discard the others','2');
INSERT INTO `CARTA` VALUES ('Tundra Rhino','Minion','Hunter','Basic','Basic','Beast','5','2','5','Your Beasts have Charge','2');
INSERT INTO `CARTA` VALUES ('Arcane Explosion','Spell','Mage','Basic','Basic',NULL,'2',NULL,NULL,'Deal 1 damage to all enemy minions','2');
INSERT INTO `CARTA` VALUES ('Arcane Intellect','Spell','Mage','Basic','Basic',NULL,'3',NULL,NULL,'Draw 2 cards','2');
INSERT INTO `CARTA` VALUES ('Arcane Missiles','Spell','Mage','Basic','Basic',NULL,'1',NULL,NULL,'Deal 3 damage randomly split among enemy characters','2');
INSERT INTO `CARTA` VALUES ('Fireball','Spell','Mage','Basic','Basic',NULL,'4',NULL,NULL,'Deal 6 damage','2');
INSERT INTO `CARTA` VALUES ('Flamestrike','Spell','Mage','Basic','Basic',NULL,'7',NULL,NULL,'Deal 4 damage to all enemy minions','2');
INSERT INTO `CARTA` VALUES ('Frost Nova','Spell','Mage','Basic','Basic',NULL,'3',NULL,NULL,'Freeze all enemy minions','2');
INSERT INTO `CARTA` VALUES ('Frostbolt','Spell','Mage','Basic','Basic',NULL,'2',NULL,NULL,'Deal 3 damage to a character and Freeze it','2');
INSERT INTO `CARTA` VALUES ('Mirror Image','Spell','Mage','Basic','Basic',NULL,'1',NULL,NULL,'Summon two 0/2 minions with Taunt','2');
INSERT INTO `CARTA` VALUES ('Polymorph','Spell','Mage','Basic','Basic',NULL,'4',NULL,NULL,'Transform a minion into a 1/1 Sheep','2');
INSERT INTO `CARTA` VALUES ('Water Elemental','Minion','Mage','Basic','Basic',NULL,'4','3','6','Freeze any character damaged by this minion','2');
INSERT INTO `CARTA` VALUES ('Blessing of Kings','Spell','Paladin','Basic','Basic',NULL,'4',NULL,NULL,'Give a minion +4/+4 (+4 Attack/+4 Health)','2');
INSERT INTO `CARTA` VALUES ('Blessing of Might','Spell','Paladin','Basic','Basic',NULL,'1',NULL,NULL,'Give a minion +3 Attack','2');
INSERT INTO `CARTA` VALUES ('Consecration','Spell','Paladin','Basic','Basic',NULL,'4',NULL,NULL,'Deal 2 damage to all enemies','2');
INSERT INTO `CARTA` VALUES ('Guardian of Kings','Minion','Paladin','Basic','Basic',NULL,'7',NULL,NULL,'Battlecry: Restore 6 Health to your hero','2');
INSERT INTO `CARTA` VALUES ('Hammer of Wrath','Spell','Paladin','Basic','Basic',NULL,'4',NULL,NULL,'Deal 3 damage. Draw a card','2');
INSERT INTO `CARTA` VALUES ('Hand of Protection','Spell','Paladin','Basic','Basic',NULL,'1',NULL,NULL,'Give a minion Divine Shield','2');
INSERT INTO `CARTA` VALUES ('Holy Light','Spell','Paladin','Basic','Basic',NULL,'2',NULL,NULL,'Restore 6 health','2');
INSERT INTO `CARTA` VALUES ('Humility','Spell','Paladin','Basic','Basic',NULL,'1',NULL,NULL,'Change a minion''s Attack to 1','2');
INSERT INTO `CARTA` VALUES ('Light''s Justice','Weapon','Paladin','Basic','Basic',NULL,'1','1','4',NULL,'2');
INSERT INTO `CARTA` VALUES ('Truesilver Champion','Weapon','Paladin','Basic','Basic',NULL,'4','4','2','Whenever your hero attacks, restore 2 Health to it','2');
INSERT INTO `CARTA` VALUES ('Divine Spirit','Spell','Priest','Basic','Basic',NULL,'2',NULL,NULL,'Double a minion''s Health','2');
INSERT INTO `CARTA` VALUES ('Holy Nova','Spell','Priest','Basic','Basic',NULL,'5',NULL,NULL,'Deal 2 damage to all enemies. Restore 2 Health to all friendly characters','2');
INSERT INTO `CARTA` VALUES ('Holy Smite','Spell','Priest','Basic','Basic',NULL,'1',NULL,NULL,'Deal 2 damage','2');
INSERT INTO `CARTA` VALUES ('Mind Blast','Spell','Priest','Basic','Basic',NULL,'2',NULL,NULL,'Deal 5 damage to the enemy hero','2');
INSERT INTO `CARTA` VALUES ('Mind Control','Spell','Priest','Basic','Basic',NULL,'10',NULL,NULL,'Take control of an enemy minion','2');
INSERT INTO `CARTA` VALUES ('Mind Vision','Spell','Priest','Basic','Basic',NULL,'1',NULL,NULL,'Put a copy of a random card in your opponent''s hand into your hand','2');
INSERT INTO `CARTA` VALUES ('Northshire Cleric','Minion','Priest','Basic','Basic',NULL,'1','1','3','Whenever a minion is healed, draw a card','2');
INSERT INTO `CARTA` VALUES ('Power Word - Shield','Spell','Priest','Basic','Basic',NULL,'1',NULL,NULL,'Give a minion +2 health. Draw a card','2');
INSERT INTO `CARTA` VALUES ('Shadow Word - Death','Spell','Priest','Basic','Basic',NULL,'3',NULL,NULL,'Destroy a minion with an Attack of 3 or more','2');
INSERT INTO `CARTA` VALUES ('Shadow Word - Pain','Spell','Priest','Basic','Basic',NULL,'2',NULL,NULL,'Destroy a minion with 3 or less Attack','2');
INSERT INTO `CARTA` VALUES ('Assassinate','Spell','Rogue','Basic','Basic',NULL,'5',NULL,NULL,'Destroy an enemy minion','2');
INSERT INTO `CARTA` VALUES ('Assassin''s Blade','Weapon','Rogue','Basic','Basic',NULL,'5','3','4',NULL,'2');
INSERT INTO `CARTA` VALUES ('Backstab','Spell','Rogue','Basic','Basic',NULL,'0',NULL,NULL,'Deal 2 damage to an undamaged minion','2');
INSERT INTO `CARTA` VALUES ('Deadly Poison','Spell','Rogue','Basic','Basic',NULL,'1',NULL,NULL,'Give your weapon +2 Attack','2');
INSERT INTO `CARTA` VALUES ('Fan of Knives','Spell','Rogue','Basic','Basic',NULL,'3',NULL,NULL,'Deal 1 damage to all enemy minions. Draw a card','2');
INSERT INTO `CARTA` VALUES ('Sap','Spell','Rogue','Basic','Basic',NULL,'2',NULL,NULL,'Return an enemy minion to your opponent''s hand','2');
INSERT INTO `CARTA` VALUES ('Shiv','Spell','Rogue','Basic','Basic',NULL,'2',NULL,NULL,'Deal 1 damage. Draw a card','2');
INSERT INTO `CARTA` VALUES ('Sinister Strike','Spell','Rogue','Basic','Basic',NULL,'1',NULL,NULL,'Deal 3 damage to the enemy hero','2');
INSERT INTO `CARTA` VALUES ('Sprint','Spell','Rogue','Basic','Basic',NULL,'7',NULL,NULL,'Draw 4 cards','2');
INSERT INTO `CARTA` VALUES ('Vanish','Spell','Rogue','Basic','Basic',NULL,'6',NULL,NULL,'Return all minion''s to their owner''s hand','2');
INSERT INTO `CARTA` VALUES ('Ancestral Healing','Spell','Shaman','Basic','Basic',NULL,'0',NULL,NULL,'Restore a minion to full Health and give it Taunt','2');
INSERT INTO `CARTA` VALUES ('Bloodlust','Spell','Shaman','Basic','Basic',NULL,'5',NULL,NULL,'Give your minions +3 Attack this turn','2');
INSERT INTO `CARTA` VALUES ('Fire Elemental','Minion','Shaman','Basic','Basic',NULL,'6','6','5','Battlecry: Deal 3 damage','2');
INSERT INTO `CARTA` VALUES ('Flametongue Totem','Minion','Shaman','Basic','Basic','Totem','2','0','3','Adjacent minions have +2 Attack','2');
INSERT INTO `CARTA` VALUES ('Frost Shock','Spell','Shaman','Basic','Basic',NULL,'1',NULL,NULL,'Deal 1 damage to an enemy character and Freeze it','2');
INSERT INTO `CARTA` VALUES ('Hex','Spell','Shaman','Basic','Basic',NULL,'3',NULL,NULL,'Transform a minion into a 0/1 Frog with Taunt','2');
INSERT INTO `CARTA` VALUES ('Rockbiter Weapon','Spell','Shaman','Basic','Basic',NULL,'1',NULL,NULL,'Give a friendly character +3 Attack this turn','2');
INSERT INTO `CARTA` VALUES ('Totemic Might','Spell','Shaman','Basic','Basic',NULL,'0',NULL,NULL,'Give your Totems +2 Health','2');
INSERT INTO `CARTA` VALUES ('Windfury','Spell','Shaman','Basic','Basic',NULL,'2',NULL,NULL,'Give a minion Windfury','2');
INSERT INTO `CARTA` VALUES ('Windspeaker','Minion','Shaman','Basic','Basic',NULL,'4','3','3','Battlecry: Give a friendly minion Windfury','2');
INSERT INTO `CARTA` VALUES ('Corruption','Spell','Warlock','Basic','Basic',NULL,'1',NULL,NULL,'Choose an enemy minion. At the start of your turn, destroy it','2');
INSERT INTO `CARTA` VALUES ('Drain Life','Spell','Warlock','Basic','Basic',NULL,'3',NULL,NULL,'Deal 2 damage. Restore 2 health to your hero','2');
INSERT INTO `CARTA` VALUES ('Dread Infernal','Minion','Warlock','Basic','Basic','Demon','6','6','6','Battlecry: Deal 1 damage to ALL other characters','2');
INSERT INTO `CARTA` VALUES ('Hellfire','Spell','Warlock','Basic','Basic',NULL,'4',NULL,NULL,'Deal 3 damage to ALL characters','2');
INSERT INTO `CARTA` VALUES ('Mortal Coil','Spell','Warlock','Basic','Basic',NULL,'1',NULL,NULL,'Deal 1 damage to a minion. If that kills it, draw a card','2');
INSERT INTO `CARTA` VALUES ('Sacrificial Pact','Spell','Warlock','Basic','Basic',NULL,'0',NULL,NULL,'Destroy a minion. Restore 5 health to your hero','2');
INSERT INTO `CARTA` VALUES ('Shadow Bolt','Spell','Warlock','Basic','Basic',NULL,'3',NULL,NULL,'Deal 4 damage to a minion','2');
INSERT INTO `CARTA` VALUES ('Soulfire','Spell','Warlock','Basic','Basic',NULL,'1',NULL,NULL,'Deal 4 damage. Discard a random card','2');
INSERT INTO `CARTA` VALUES ('Succubus','Minion','Warlock','Basic','Basic','Demon','2','4','3','Battlecry: Discard a random card','2');
INSERT INTO `CARTA` VALUES ('Voidwalker','Minion','Warlock','Basic','Basic','Demon','1','1','3','Taunt','2');
INSERT INTO `CARTA` VALUES ('Arcanite Reaper','Weapon','Warrior','Basic','Basic',NULL,'5','5','2',NULL,'2');
INSERT INTO `CARTA` VALUES ('Charge','Spell','Warrior','Basic','Basic',NULL,'3',NULL,NULL,'Give a friendly minion +2 Attack and Charge','2');
INSERT INTO `CARTA` VALUES ('Cleave','Spell','Warrior','Basic','Basic',NULL,'2',NULL,NULL,'Deal 2 damage to two random enemy minions','2');
INSERT INTO `CARTA` VALUES ('Execute','Spell','Warrior','Basic','Basic',NULL,'1',NULL,NULL,'Destroy a damaged enemy minion','2');
INSERT INTO `CARTA` VALUES ('Fiery War Axe','Weapon','Warrior','Basic','Basic',NULL,'2','3','2',NULL,'2');
INSERT INTO `CARTA` VALUES ('Heroic Strike','Spell','Warrior','Basic','Basic',NULL,'2',NULL,NULL,'Give your hero +4 Attack this turn','2');
INSERT INTO `CARTA` VALUES ('Kor''kron Elite','Minion','Warrior','Basic','Basic',NULL,'4','4','3','Charge','2');
INSERT INTO `CARTA` VALUES ('Shield Block','Spell','Warrior','Basic','Basic',NULL,'3',NULL,NULL,'Gain 5 armor. Draw a card','2');
INSERT INTO `CARTA` VALUES ('Warsong Commander','Minion','Warrior','Basic','Basic',NULL,'3','2','3','Whenever you summon a minion with 3 or less Attack, give it Charge','2');
INSERT INTO `CARTA` VALUES ('Whirlwind','Spell','Warrior','Basic','Basic',NULL,'1',NULL,NULL,'Deal 1 damage to ALL minions','2');
INSERT INTO `CARTA` VALUES ('Abomination','Minion','Neutral','Classic','Rare',NULL,'5','4','4','Taunt. Deathrattle: Deal 2 damage to ALL characters','0');
INSERT INTO `CARTA` VALUES ('Abusive Sergeant','Minion','Neutral','Classic','Common',NULL,'1','2','1','Battlecry: Give a minion +2 Attack this turn','0');
INSERT INTO `CARTA` VALUES ('Acolyte of Pain','Minion','Neutral','Classic','Common',NULL,'3','1','3','Whenever this minion takes damage, draw a card','0');
INSERT INTO `CARTA` VALUES ('Alarm-o-Bot','Minion','Neutral','Classic','Rare','Mech','3','0','3','At the start of your turn, swap this minion with a random one in your hand','0');
INSERT INTO `CARTA` VALUES ('Alexstrasza','Minion','Neutral','Classic','Legendary','Dragon','9','8','8','Battlecry: Set a hero''s remaining Health to 15','0');
INSERT INTO `CARTA` VALUES ('Amani Berserker','Minion','Neutral','Classic','Common',NULL,'2','2','3','Enrage: +3 Attack','0');
INSERT INTO `CARTA` VALUES ('Ancient Brewmaster','Minion','Neutral','Classic','Common',NULL,'4','5','4','Battlecry: Return a friendly minion from the battlefield to your hand','0');
INSERT INTO `CARTA` VALUES ('Ancient Mage','Minion','Neutral','Classic','Rare',NULL,'4','2','5','Battlecry: Give adjacent minions +1 Spell Damage','0');
INSERT INTO `CARTA` VALUES ('Ancient Watcher','Minion','Neutral','Classic','Rare',NULL,'2','4','5','Can''t Attack','0');
INSERT INTO `CARTA` VALUES ('Angry Chicken','Minion','Neutral','Classic','Rare','Beast','1','1','1','Enrage: +5 Attack','0');
INSERT INTO `CARTA` VALUES ('Arcane Golem','Minion','Neutral','Classic','Rare',NULL,'3','4','2','Charge. Battlecry: Give your opponent a Mana Crystal','0');
INSERT INTO `CARTA` VALUES ('Argent Commander','Minion','Neutral','Classic','Rare',NULL,'6','4','2','Charge, Divine Shield','0');
INSERT INTO `CARTA` VALUES ('Argent Squire','Minion','Neutral','Classic','Common',NULL,'1','1','1','Divine Shield','0');
INSERT INTO `CARTA` VALUES ('Azure Drake','Minion','Neutral','Classic','Rare','Dragon','5','4','4','Spell Damage +1, Battlecry: Draw a card','0');
INSERT INTO `CARTA` VALUES ('Baron Geddon','Minion','Neutral','Classic','Legendary',NULL,'7','7','5','At the end of your turn, deal 2 damage to ALL other characters','0');
INSERT INTO `CARTA` VALUES ('Big Game Hunter','Minion','Neutral','Classic','Epic',NULL,'3','4','2','Battlecry: Destroy a minion with an Attack of 7 or more','0');
INSERT INTO `CARTA` VALUES ('Blood Knight','Minion','Neutral','Classic','Epic',NULL,'3','3','3','Battlecry: All minios lose Divine Shield. Gain +3/+3 for each Shield lost','0');
INSERT INTO `CARTA` VALUES ('Bloodmage Thalnos','Minion','Neutral','Classic','Legendary',NULL,'2','1','1','Spell Damage +1, Deathrattle: Draw a card','0');
INSERT INTO `CARTA` VALUES ('Bloodsail Corsair','Minion','Neutral','Classic','Rare','Pirate','1','1','2','Battlecry: Remove 1 Durability from your opponent''s weapon','0');
INSERT INTO `CARTA` VALUES ('Bloodsail Raider','Minion','Neutral','Classic','Common','Pirate','2','2','3','Battlecry: Gain attack equal to the Attack of your weapon','0');
INSERT INTO `CARTA` VALUES ('Cairne Bloodhoof','Minion','Neutral','Classic','Legendary',NULL,'6','4','5','Deathrattle: Summon a 4/5 Baine Bloodhoof','0');
INSERT INTO `CARTA` VALUES ('Captain Greenskin','Minion','Neutral','Classic','Legendary','Pirate','5','5','4','Battlecry: Give your weapon +1/+1','0');
INSERT INTO `CARTA` VALUES ('Coldlight Oracle','Minion','Neutral','Classic','Rare','Murloc','3','2','2','Battlecry: Each player draws 2 cards','0');
INSERT INTO `CARTA` VALUES ('Coldlight Seer','Minion','Neutral','Classic','Rare','Murloc','3','2','3','Battlecry: Give ALL other Murlocs +2 Health','0');
INSERT INTO `CARTA` VALUES ('Crazed Alchemist','Minion','Neutral','Classic','Rare',NULL,'2','2','2','Battlecry: Swap the Attack and Health of a minion','0');
INSERT INTO `CARTA` VALUES ('Cult Master','Minion','Neutral','Classic','Common',NULL,'4','4','2','Whenever one of your other minions die, draw a card','0');
INSERT INTO `CARTA` VALUES ('Dark Iron Dwarf','Minion','Neutral','Classic','Common',NULL,'4','4','4','Battlecry: Give a minion +2 Attack this turn','0');
INSERT INTO `CARTA` VALUES ('Deathwing','Minion','Neutral','Classic','Legendary','Dragon','10','12','12','Battlecry: Destroy all other minions and discard your hand','0');
INSERT INTO `CARTA` VALUES ('Defender of Argus','Minion','Neutral','Classic','Rare',NULL,'4','2','3','Battlecry: Give adjacent minions +1/+1 and Taunt','0');
INSERT INTO `CARTA` VALUES ('Demolisher','Minion','Neutral','Classic','Rare','Mech','3','1','4','At the start of your turn, deal 2 damage to a random enemy','0');
INSERT INTO `CARTA` VALUES ('Dire Wolf Alpha','Minion','Neutral','Classic','Common','Beast','2','2','2','Adjacent minions have +1 Attack','0');
INSERT INTO `CARTA` VALUES ('Doomsayer','Minion','Neutral','Classic','Epic',NULL,'2','0','7','At the start of your turn, destroy ALL minions','0');
INSERT INTO `CARTA` VALUES ('Dread Corsair','Minion','Neutral','Classic','Common','Pirate','4','3','3','Taunt. Costs (1) less per Attack of your weapon','0');
INSERT INTO `CARTA` VALUES ('Earthen Ring Farseer','Minion','Neutral','Classic','Common',NULL,'3','3','3','Battlecry: Restore 3 Health','0');
INSERT INTO `CARTA` VALUES ('Emperor Cobra','Minion','Neutral','Classic','Rare','Beast','3','2','3','Destroy any minion damaged by this minion','0');
INSERT INTO `CARTA` VALUES ('Faceless Manipulator','Minion','Neutral','Classic','Epic',NULL,'5','3','3','Battlecry: Choose a minion and become a copy of it','0');
INSERT INTO `CARTA` VALUES ('Faerie Dragon','Minion','Neutral','Classic','Common','Dragon','2','3','2','Can''t be targetted by spells or Hero Powers','0');
INSERT INTO `CARTA` VALUES ('Fen Creeper','Minion','Neutral','Classic','Common',NULL,'5','3','6','Taunt','0');
INSERT INTO `CARTA` VALUES ('Flesheating Ghoul','Minion','Neutral','Classic','Common',NULL,'3','2','3','Whenever a minion dies, gain +1 Attack','0');
INSERT INTO `CARTA` VALUES ('Frost Elemental','Minion','Neutral','Classic','Common',NULL,'6','5','5','Battlecry: Freeze a character','0');
INSERT INTO `CARTA` VALUES ('Gadgetzan Auctioneer','Minion','Neutral','Classic','Rare',NULL,'6','4','4','Whenever you cast a spell, draw a card','0');
INSERT INTO `CARTA` VALUES ('Gruul','Minion','Neutral','Classic','Legendary',NULL,'8','7','7','At the end of each turn, gain +1/+1','0');
INSERT INTO `CARTA` VALUES ('Harrison Jones','Minion','Neutral','Classic','Legendary',NULL,'5','5','4','Battlecry: Destroy your opponent''s weapon and draw cards equal to its Durability','0');
INSERT INTO `CARTA` VALUES ('Harvest Golem','Minion','Neutral','Classic','Common','Mech','3','2','3','Deathrattle: Summon a 2/1 Damaged Golem','0');
INSERT INTO `CARTA` VALUES ('Hogger','Minion','Neutral','Classic','Legendary',NULL,'6','4','4','At the end of your turn, summon a 2/2 Gnoll with Taunt','0');
INSERT INTO `CARTA` VALUES ('Hungry Crab','Minion','Neutral','Classic','Epic','Beast','1','1','2','Battlecry: Destroy a Murloc and gain +2/+2','0');
INSERT INTO `CARTA` VALUES ('Illidan Stormrage','Minion','Neutral','Classic','Legendary','Demon','6','7','5','Whenever you play a card, summon a 2/1 Flame of Azzinoth','0');
INSERT INTO `CARTA` VALUES ('Imp Master','Minion','Neutral','Classic','Common',NULL,'3','1','5','At the end of your turn, deal 1 damage to this minion and summon a 1/1 imp','0');
INSERT INTO `CARTA` VALUES ('Injured Blademaster','Minion','Neutral','Classic','Rare',NULL,'3','4','7','Battlecry: Deal 4 damage to HIMSELF','0');
INSERT INTO `CARTA` VALUES ('Ironbeak Owl','Minion','Neutral','Classic','Common','Beast','2','2','1','Battlecry: Silence a minion','0');
INSERT INTO `CARTA` VALUES ('Jungle Panther','Minion','Neutral','Classic','Common',NULL,'3','4','2','Stealth','0');
INSERT INTO `CARTA` VALUES ('King Mukla','Minion','Neutral','Classic','Legendary','Beast','3','5','5','Battlecry: Give your opponnet 2 Bananas','0');
INSERT INTO `CARTA` VALUES ('Knife Juggler','Minion','Neutral','Classic','Rare',NULL,'2','3','2','After you summon a minion, deal 1 damage to a random enemy','0');
INSERT INTO `CARTA` VALUES ('Leeroy Jenkins','Minion','Neutral','Classic','Legendary',NULL,'5','6','2','Charge. Battlecry: Summon two 1/1 Whelps for your opponent','0');
INSERT INTO `CARTA` VALUES ('Leper Gnome','Minion','Neutral','Classic','Common',NULL,'1','2','1','Deathrattle: Deal 2 damage to the enemy hero','0');
INSERT INTO `CARTA` VALUES ('Lightwarden','Minion','Neutral','Classic','Rare',NULL,'1','1','2','Whenever a character is healed, gain +2 Attack','0');
INSERT INTO `CARTA` VALUES ('Loot Hoarder','Minion','Neutral','Classic','Common',NULL,'2','2','1','Deathrattle: Draw a card','0');
INSERT INTO `CARTA` VALUES ('Lorewalker Cho','Minion','Neutral','Classic','Legendary',NULL,'2','0','4','Whenever a player cast a spell, put a copy into the other player''s hand','0');
INSERT INTO `CARTA` VALUES ('Mad Bomber','Minion','Neutral','Classic','Common',NULL,'2','3','2','Battlecry: Deal 3 damage randomly split between all other characters','0');
INSERT INTO `CARTA` VALUES ('Malygos','Minion','Neutral','Classic','Legendary','Dragon','9','4','12','Spell Damage +5','0');
INSERT INTO `CARTA` VALUES ('Mana Addict','Minion','Neutral','Classic','Rare',NULL,'2','1','3','Whenever you cast a spell, gain +2 Attack this turn','0');
INSERT INTO `CARTA` VALUES ('Mana Wraith','Minion','Neutral','Classic','Rare',NULL,'2','2','2','ALL minions costs (1) more','0');
INSERT INTO `CARTA` VALUES ('Master Swordsmith','Minion','Neutral','Classic','Rare',NULL,'2','1','3','At the end of your turn, give another friendly minion +1 Attack','0');
INSERT INTO `CARTA` VALUES ('Millhouse Manastorm','Minion','Neutral','Classic','Legendary',NULL,'2','4','4','Battlecry: Enemy spells cost (0) next turn','0');
INSERT INTO `CARTA` VALUES ('Mind Control Tech','Minion','Neutral','Classic','Rare',NULL,'3','3','3','Battlecry: If your opponent has 4 or more minions, take control of one at random','0');
INSERT INTO `CARTA` VALUES ('Mogu''shan Warden','Minion','Neutral','Classic','Common',NULL,'4','1','7','Taunt','0');
INSERT INTO `CARTA` VALUES ('Molten Giant','Minion','Neutral','Classic','Epic',NULL,'20','8','8','Costs (1) less for each damage your hero has taken','0');
INSERT INTO `CARTA` VALUES ('Mountain Giant','Minion','Neutral','Classic','Epic',NULL,'12','8','8','Costs (1) less for each other card in your hand','0');
INSERT INTO `CARTA` VALUES ('Murloc Tidecaller','Minion','Neutral','Classic','Rare','Murloc','1','1','2','Whenever a Murloc is summoned, gain +1 Attack','0');
INSERT INTO `CARTA` VALUES ('Murloc Warleader','Minion','Neutral','Classic','Epic','Murloc','3','3','3','ALL other Murlocs have +2/+1','0');
INSERT INTO `CARTA` VALUES ('Nat Pagle','Minion','Neutral','Classic','Legendary',NULL,'2','0','4','At the start of your turn, you have a 50% chance to draw an extra card','0');
INSERT INTO `CARTA` VALUES ('Nozdormu','Minion','Neutral','Classic','Legendary','Dragon','9','8','8','Players only have 15 seconds to take their turns','0');
INSERT INTO `CARTA` VALUES ('Onyxia','Minion','Neutral','Classic','Legendary','Dragon','9','8','8','Battlecry: Summon 1/1 Whelps until your side of the battlefield is full','0');
INSERT INTO `CARTA` VALUES ('Pint-Sized Summoner','Minion','Neutral','Classic','Rare',NULL,'2','2','2','The first minion you play each turn costs (1) less','0');
INSERT INTO `CARTA` VALUES ('Priestess of Elune','Minion','Neutral','Classic','Common',NULL,'6','5','4','Battlecry: Restore 4 Health to your hero','0');
INSERT INTO `CARTA` VALUES ('Questing Adventurer','Minion','Neutral','Classic','Rare',NULL,'3','2','2','Whenever you play a card, gain +1/+1','0');
INSERT INTO `CARTA` VALUES ('Raging Worgen','Minion','Neutral','Classic','Common',NULL,'3','3','3','Enrage: Windfury and +1 Attack','0');
INSERT INTO `CARTA` VALUES ('Ragnaros the Firelord','Minion','Neutral','Classic','Legendary',NULL,'8','8','8','Can''t Attack. At the end of your turn, deal 8 damage to a random enemy','0');
INSERT INTO `CARTA` VALUES ('Ravenholdt Assassin','Minion','Neutral','Classic','Rare',NULL,'7','7','5','Stealth','0');
INSERT INTO `CARTA` VALUES ('Scarlet Crusader','Minion','Neutral','Classic','Common',NULL,'3','3','1','Divine Shield','0');
INSERT INTO `CARTA` VALUES ('Sea Giant','Minion','Neutral','Classic','Epic',NULL,'10','8','8','Costs (1) less for each other minion on the battlefield','0');
INSERT INTO `CARTA` VALUES ('Secretkeeper','Minion','Neutral','Classic','Rare',NULL,'1','1','2','Whenever a secret is played, gain +1/+1','0');
INSERT INTO `CARTA` VALUES ('Shieldbearer','Minion','Neutral','Classic','Common',NULL,'1','0','4','Taunt','0');
INSERT INTO `CARTA` VALUES ('Silver Hand Knight','Minion','Neutral','Classic','Common',NULL,'5','4','4','Battlecry: Summon a 2/2 Squire','0');
INSERT INTO `CARTA` VALUES ('Silvermoon Guardian','Minion','Neutral','Classic','Common',NULL,'4','3','3','Divine Shield','0');
INSERT INTO `CARTA` VALUES ('Southsea Captain','Minion','Neutral','Classic','Epic','Pirate','3','3','3','Your other Pirates have +1/+1','0');
INSERT INTO `CARTA` VALUES ('Southsea Deckhand','Minion','Neutral','Classic','Common','Pirate','1','2','1','Has Charge while you have a weapon equipped','0');
INSERT INTO `CARTA` VALUES ('Spellbreaker','Minion','Neutral','Classic','Common',NULL,'4','4','3','Battlecry: Silence a minion','0');
INSERT INTO `CARTA` VALUES ('Spiteful Smith','Minion','Neutral','Classic','Common',NULL,'5','4','6','Enrage: Your weapon has +2 Attack','0');
INSERT INTO `CARTA` VALUES ('Stampeding Kodo','Minion','Neutral','Classic','Rare','Beast','5','3','5','Battlecry: Destroy a random enemy minion with 2 or less Attack','0');
INSERT INTO `CARTA` VALUES ('Stranglethorn Tiger','Minion','Neutral','Classic','Common','Beast','5','5','5','Stealth','0');
INSERT INTO `CARTA` VALUES ('Sunfury Protector','Minion','Neutral','Classic','Rare',NULL,'2','2','3','Battlecry: Give adjacent minions Taunt','0');
INSERT INTO `CARTA` VALUES ('Sunwalker','Minion','Neutral','Classic','Rare',NULL,'6','4','5','Taunt. Divine Shield','0');
INSERT INTO `CARTA` VALUES ('Sylvanas Windrunner','Minion','Neutral','Classic','Legendary',NULL,'6','5','5','Deathrattle: Take control of a random enemy minion','0');
INSERT INTO `CARTA` VALUES ('Tauren Warrior','Minion','Neutral','Classic','Common',NULL,'3','2','3','Taunt. Enrage: +3 Attack','0');
INSERT INTO `CARTA` VALUES ('The Beast','Minion','Neutral','Classic','Legendary','Beast','6','9','7','Deathrattle: Summon a 3/3 Finkle Einhorn for your opponent','0');
INSERT INTO `CARTA` VALUES ('The Black Knight','Minion','Neutral','Classic','Legendary',NULL,'6','4','5','Battlecry: Destroy an enemy minion with Taunt','0');
INSERT INTO `CARTA` VALUES ('Thrallmar Farseer','Minion','Neutral','Classic','Common',NULL,'3','2','3','Windfury','0');
INSERT INTO `CARTA` VALUES ('Tinkmaster Overspark','Minion','Neutral','Classic','Legendary',NULL,'3','3','3','Battlecry: Transform another random minion into a 5/5 Devilsaur or a 1/1 Squirrel','0');
INSERT INTO `CARTA` VALUES ('Twilight Drake','Minion','Neutral','Classic','Rare','Dragon','4','4','1','Battlecry: Gain +1 Health for each other card in your hand','0');
INSERT INTO `CARTA` VALUES ('Venture Co. Mercenary','Minion','Neutral','Classic','Common',NULL,'5','7','6','Your minions costs (3) more','0');
INSERT INTO `CARTA` VALUES ('Violet Teacher','Minion','Neutral','Classic','Rare',NULL,'4','3','5','Whenever you cast a spell, summon a 1/1 Violet Apprentice','0');
INSERT INTO `CARTA` VALUES ('Wild Pyromancer','Minion','Neutral','Classic','Rare',NULL,'2','3','2','After you cast a spell, deal 1 damage to ALL minions','0');
INSERT INTO `CARTA` VALUES ('Windfury Harpy','Minion','Neutral','Classic','Common',NULL,'6','4','5','Windfury','0');
INSERT INTO `CARTA` VALUES ('Wisp','Minion','Neutral','Classic','Common',NULL,'0','1','1',NULL,'0');
INSERT INTO `CARTA` VALUES ('Worgen Infiltrator','Minion','Neutral','Classic','Common',NULL,'1','2','1','Stealth','0');
INSERT INTO `CARTA` VALUES ('Young Dragonhawk','Minion','Neutral','Classic','Common','Beast','1','1','1','Windfury','0');
INSERT INTO `CARTA` VALUES ('Young Priestess','Minion','Neutral','Classic','Rare',NULL,'1','2','1','At the end of your turn, give another random friendly minion +1 Health','0');
INSERT INTO `CARTA` VALUES ('Youthful Brewmaster','Minion','Neutral','Classic','Common',NULL,'2','3','2','Battlecry: Return a friendly minion from the battlefield to your hand','0');
INSERT INTO `CARTA` VALUES ('Ysera','Minion','Neutral','Classic','Legendary','Dragon','9','4','12','At the end of your turn, draw a Dream Card','0');
INSERT INTO `CARTA` VALUES ('Ancient of Lore','Minion','Druid','Classic','Epic',NULL,'7','5','5','Choose One - Draw 2 cards; or Restore 5 Heath','0');
INSERT INTO `CARTA` VALUES ('Ancient of War','Minion','Druid','Classic','Epic',NULL,'7','5','5','Choose One - +5 Attack; or +5 Health and Taunt','0');
INSERT INTO `CARTA` VALUES ('Bite','Spell','Druid','Classic','Rare',NULL,'4',NULL,NULL,'Give your Hero +4 Attack this turn and 4 Armor','0');
INSERT INTO `CARTA` VALUES ('Cenarius','Minion','Druid','Classic','Legendary',NULL,'9','5','8','Choose One - Give your other minions +2/+2; or summon two 2/2 Treants with Taunt','0');
INSERT INTO `CARTA` VALUES ('Druid of the Claw','Minion','Druid','Classic','Common',NULL,'5','4','4','Choose One - Charge; or +2 Health and Taunt','0');
INSERT INTO `CARTA` VALUES ('Force of Nature','Spell','Druid','Classic','Epic',NULL,'6',NULL,NULL,'Summon three 2/2 Treants with Charge that die at the end of the turn','0');
INSERT INTO `CARTA` VALUES ('Keeper of the Grove','Minion','Druid','Classic','Rare',NULL,'4','2','4','Choose One - Deal 2 Damage; or Silence a minion','0');
INSERT INTO `CARTA` VALUES ('Mark of Nature','Spell','Druid','Classic','Common',NULL,'3',NULL,NULL,'Choose One - Give a minion +4; or +4 Health and Taunt','0');
INSERT INTO `CARTA` VALUES ('Naturalize','Spell','Druid','Classic','Common',NULL,'1',NULL,NULL,'Destroy a minion. Your opponent draws 2 cards','0');
INSERT INTO `CARTA` VALUES ('Nourish','Spell','Druid','Classic','Rare',NULL,'5',NULL,NULL,'Choose One - Gain 2 Mana Crystals; or Draw 3 cards','0');
INSERT INTO `CARTA` VALUES ('Power of the Wild','Spell','Druid','Classic','Common',NULL,'2',NULL,NULL,'Choose One - Give your minions +1/+1; or Summon a 3/2 Panther','0');
INSERT INTO `CARTA` VALUES ('Savagery','Spell','Druid','Classic','Rare',NULL,'1',NULL,NULL,'Deal damage equal to your hero''s Attack to a minion','0');
INSERT INTO `CARTA` VALUES ('Soul of the Forest','Spell','Druid','Classic','Common',NULL,'4',NULL,NULL,'Give your minions Deathrattle: Summon a 2/2 Treant','0');
INSERT INTO `CARTA` VALUES ('Starfall','Spell','Druid','Classic','Rare',NULL,'5',NULL,NULL,'Choose One - Deal 5 damge to a minion; or 2 damage to all enemy minions','0');
INSERT INTO `CARTA` VALUES ('Wrath','Spell','Druid','Classic','Common',NULL,'2',NULL,NULL,'Choose One - Deal 3 damage to a minion; or deal 1 damage and draw a card','0');
INSERT INTO `CARTA` VALUES ('Bestial Wrath','Spell','Hunter','Classic','Epic',NULL,'1',NULL,NULL,'Give a Beast +2 Attack and Inmune this turn','0');
INSERT INTO `CARTA` VALUES ('Deadly Shot','Spell','Hunter','Classic','Common',NULL,'3',NULL,NULL,'Destroy a random enemy minion','0');
INSERT INTO `CARTA` VALUES ('Eaglehorn Bow','Weapon','Hunter','Classic','Rare',NULL,'3','3','2','Whenever a friendly secret is revealed, gain +1 Durability','0');
INSERT INTO `CARTA` VALUES ('Explosive Shot','Spell','Hunter','Classic','Rare',NULL,'5',NULL,NULL,'Deal 5 damage to a minion and 2 damage to adjacent ones','0');
INSERT INTO `CARTA` VALUES ('Explosive Trap','Spell','Hunter','Classic','Common',NULL,'2',NULL,NULL,'Secret: When your hero is attacked, deal 2 damage to all enemies','0');
INSERT INTO `CARTA` VALUES ('Flare','Spell','Hunter','Classic','Rare',NULL,'2',NULL,NULL,'All minions lose Stelath. Destroy all enemy Secrets. Draw a card','0');
INSERT INTO `CARTA` VALUES ('Freezing Trap','Spell','Hunter','Classic','Common',NULL,'2',NULL,NULL,'Secret: When an enmy minion attacks, return it to its owner''s hand and it costs (2) more','0');
INSERT INTO `CARTA` VALUES ('Gladiator''s Longbow','Weapon','Hunter','Classic','Epic',NULL,'7','5','2','Your hero is Inmune while attacking','0');
INSERT INTO `CARTA` VALUES ('King Krush','Minion','Hunter','Classic','Legendary','Beast','9','8','8','Charge','0');
INSERT INTO `CARTA` VALUES ('Misdirection','Spell','Hunter','Classic','Rare',NULL,'2',NULL,NULL,'Secret: When a character attacks your hero, instead he attacks another random character','0');
INSERT INTO `CARTA` VALUES ('Savannah Highmane','Minion','Hunter','Classic','Rare','Beast','6','6','5','Deathrattle: Summon two 2/2 Hyenas','0');
INSERT INTO `CARTA` VALUES ('Scavenging Hyena','Minion','Hunter','Classic','Common','Beast','2','2','2','Whenever a friendly Beast dies, gain +2/+1','0');
INSERT INTO `CARTA` VALUES ('Snake Trap','Spell','Hunter','Classic','Epic',NULL,'2',NULL,NULL,'Secret: When one of your minions is attacked, summon three 1/1 Snakes','0');
INSERT INTO `CARTA` VALUES ('Snipe','Spell','Hunter','Classic','Common',NULL,'2',NULL,NULL,'Secret: When your opponent plays a minion, deal 4 damage to it','0');
INSERT INTO `CARTA` VALUES ('Unleash the Hounds','Spell','Hunter','Classic','Common',NULL,'3',NULL,NULL,'For each enemy minion, summon a 1/1 Hound with Charge','0');
INSERT INTO `CARTA` VALUES ('Archmage Antonidas','Minion','Mage','Classic','Legendary',NULL,'7','5','7','Whenever you cast a spell, add a ''Fireball'' spell to your hand','0');
INSERT INTO `CARTA` VALUES ('Blizzard','Spell','Mage','Classic','Rare',NULL,'6',NULL,NULL,'Deal 2 damage to all enemy minions and Freeze them','0');
INSERT INTO `CARTA` VALUES ('Cone of Cold','Spell','Mage','Classic','Common',NULL,'4',NULL,NULL,'Freeze a minion and the minions next to it, and deal 1 damage to them','0');
INSERT INTO `CARTA` VALUES ('Counterspell','Spell','Mage','Classic','Rare',NULL,'3',NULL,NULL,'Secret: When your opponent casts a spell, Counter it','0');
INSERT INTO `CARTA` VALUES ('Ethereal Arcanist','Minion','Mage','Classic','Rare',NULL,'4','3','3','If you control a Secret at the end of the turn, gain +2/+2','0');
INSERT INTO `CARTA` VALUES ('Ice Barrier','Spell','Mage','Classic','Common',NULL,'3',NULL,NULL,'Secret: When your hero is attacked, gain 8 Armor','0');
INSERT INTO `CARTA` VALUES ('Ice Block','Spell','Mage','Classic','Epic',NULL,'3',NULL,NULL,'Secret: When your hero takes fatal damage, prevent it and become Inmune this turn','0');
INSERT INTO `CARTA` VALUES ('Ice Lance','Spell','Mage','Classic','Common',NULL,'1',NULL,NULL,'Freeze a Character. If it was already Frozen, deal 4 damage instead','0');
INSERT INTO `CARTA` VALUES ('Kirin Tor Mage','Minion','Mage','Classic','Rare',NULL,'3','4','3','Battlecry: The next secret you play this turn costs (0)','0');
INSERT INTO `CARTA` VALUES ('Mana Wyrm','Minion','Mage','Classic','Common',NULL,'1','1','3','Whenever you cast a spell, gain +1 Attack','0');
INSERT INTO `CARTA` VALUES ('Mirror Entity','Spell','Mage','Classic','Common',NULL,'3',NULL,NULL,'Secret: When your opponent plays a minion, summon a copy of it','0');
INSERT INTO `CARTA` VALUES ('Pyroblast','Spell','Mage','Classic','Epic',NULL,'10',NULL,NULL,'Deal 10 damage','0');
INSERT INTO `CARTA` VALUES ('Sorcerer''s Apprentice','Minion','Mage','Classic','Common',NULL,'2','3','2','Your spells costs (1) less','0');
INSERT INTO `CARTA` VALUES ('Spellbender','Spell','Mage','Classic','Epic',NULL,'3',NULL,NULL,'Secret: When an enemy casts a spell on a minion, summon a 1/3 as the new target','0');
INSERT INTO `CARTA` VALUES ('Vaporize','Spell','Mage','Classic','Rare',NULL,'3',NULL,NULL,'Secret: When a minion attacks your hero, destroy it','0');
INSERT INTO `CARTA` VALUES ('Aldor Peacekeeper','Minion','Paladin','Classic','Rare',NULL,'3','3','3','Battlecry: Change an enemy minion''s Attack to 1','0');
INSERT INTO `CARTA` VALUES ('Argent Protector','Minion','Paladin','Classic','Common',NULL,'2','2','2','Battlecry: Give a friendly minion Divine Shield','0');
INSERT INTO `CARTA` VALUES ('Avenging Wrath','Spell','Paladin','Classic','Epic',NULL,'6',NULL,NULL,'Deal 8 damage randomly split among enemy characters','0');
INSERT INTO `CARTA` VALUES ('Blessed Champion','Spell','Paladin','Classic','Rare',NULL,'5',NULL,NULL,'Double a minion''s Attack','0');
INSERT INTO `CARTA` VALUES ('Blessing of Widsom','Spell','Paladin','Classic','Common',NULL,'1',NULL,NULL,'Choose a minion. Whenever it attacks, draw a card','0');
INSERT INTO `CARTA` VALUES ('Divine Favor','Spell','Paladin','Classic','Rare',NULL,'3',NULL,NULL,'Draw cards until you have as many in your hand as your opponent','0');
INSERT INTO `CARTA` VALUES ('Equality','Spell','Paladin','Classic','Rare',NULL,'2',NULL,NULL,'Change the Health of ALL minions to 1','0');
INSERT INTO `CARTA` VALUES ('Eye for an Eye','Spell','Paladin','Classic','Common',NULL,'1',NULL,NULL,'Secret: When your hero takes damage, deal that much damage to the enemy hero','0');
INSERT INTO `CARTA` VALUES ('Holy Wrath','Spell','Paladin','Classic','Rare',NULL,'5',NULL,NULL,'Draw a card and deal damage equal to its cost','0');
INSERT INTO `CARTA` VALUES ('Lay on Hands','Spell','Paladin','Classic','Epic',NULL,'8',NULL,NULL,'Restore 8 Health. Draw 3 cards','0');
INSERT INTO `CARTA` VALUES ('Noble Sacrifice','Spell','Paladin','Classic','Common',NULL,'1',NULL,NULL,'Secret: When an enemy attacks, summon a 2/1 Defender as the new target','0');
INSERT INTO `CARTA` VALUES ('Redemption','Spell','Paladin','Classic','Common',NULL,'1',NULL,NULL,'Secret: When one of your minions dies, return it to life with 1 Health','0');
INSERT INTO `CARTA` VALUES ('Repentance','Spell','Paladin','Classic','Common',NULL,'1',NULL,NULL,'Secret: When your opponent plays a minion, reduce its Health to 1','0');
INSERT INTO `CARTA` VALUES ('Sword of Justice','Weapon','Paladin','Classic','Epic',NULL,'3','1','5','Whenever you summon a minion, give it +1/+1 and this loses 1 Durability','0');
INSERT INTO `CARTA` VALUES ('Tirion Fordring','Minion','Paladin','Classic','Legendary',NULL,'8','6','6','Divine Shield. Taunt. Deathrattle: Equip a 5/3 Ashbringer','0');
INSERT INTO `CARTA` VALUES ('Auchenai Soulpriest','Minion','Priest','Classic','Rare',NULL,'4','3','5','Your cards and powers that restore Health now deal damage instead','0');
INSERT INTO `CARTA` VALUES ('Cabal Shadow Priest','Minion','Priest','Classic','Epic',NULL,'6','4','5','Battlecry: Take control of an enemy minion that has 2 or less Attack','0');
INSERT INTO `CARTA` VALUES ('Circle of Healing','Spell','Priest','Classic','Common',NULL,'0',NULL,NULL,'Restore 4 Health to ALL characters','0');
INSERT INTO `CARTA` VALUES ('Holy Fire','Spell','Priest','Classic','Rare',NULL,'6',NULL,NULL,'Deal 5 damage. Restore 5 Health to your hero','0');
INSERT INTO `CARTA` VALUES ('Inner Fire','Spell','Priest','Classic','Common',NULL,'1',NULL,NULL,'Change a minion''s Attack to be equal to its Health','0');
INSERT INTO `CARTA` VALUES ('Lightspawn','Minion','Priest','Classic','Common',NULL,'4','0','5','This minion''s Attack is always equal to its Health','0');
INSERT INTO `CARTA` VALUES ('Lightwell','Minion','Priest','Classic','Rare',NULL,'2','0','5','At the start of your turn, restore 3 Health to a damaged friendly character','0');
INSERT INTO `CARTA` VALUES ('Mass Dispel','Spell','Priest','Classic','Rare',NULL,'4',NULL,NULL,'Silence all enemy minions. Draw a card','0');
INSERT INTO `CARTA` VALUES ('Mindgames','Spell','Priest','Classic','Epic',NULL,'4',NULL,NULL,'Put a copy of a random minion from your opponent''s deck into the battlefield','0');
INSERT INTO `CARTA` VALUES ('Prophet Velen','Minion','Priest','Classic','Legendary',NULL,'7',NULL,NULL,'Double the damage and healing of your spells and hero powers','0');
INSERT INTO `CARTA` VALUES ('Shadow Madness','Spell','Priest','Classic','Rare',NULL,'4',NULL,NULL,'Gain control of an enemy minion with 3 or less Attack until end of turn','0');
INSERT INTO `CARTA` VALUES ('Shadowform','Spell','Priest','Classic','Epic',NULL,'3',NULL,NULL,'Your Hero Power becomes ''Deal 2 damage''. If already in Shadowform: 3 damage','0');
INSERT INTO `CARTA` VALUES ('Silence','Spell','Priest','Classic','Common',NULL,'0',NULL,NULL,'Silence a minion','0');
INSERT INTO `CARTA` VALUES ('Temple Enforcer','Minion','Priest','Classic','Common',NULL,'6','6','6','Battlecry: Give a friendly minion +3 Health','0');
INSERT INTO `CARTA` VALUES ('Thoughtsteal','Spell','Priest','Classic','Common',NULL,'3',NULL,NULL,'Copy 2 cards from your opponent''s deck and put them into your hand','0');
INSERT INTO `CARTA` VALUES ('Betrayal','Spell','Rogue','Classic','Common',NULL,'2',NULL,NULL,'Force an enemy minion to deal its damage to the minions next to it','0');
INSERT INTO `CARTA` VALUES ('Blade Flurry','Spell','Rogue','Classic','Rare',NULL,'2',NULL,NULL,'Destroy your weapon and deal its damage to all enemies','0');
INSERT INTO `CARTA` VALUES ('Cold Blood','Spell','Rogue','Classic','Common',NULL,'1',NULL,NULL,'Give a minion +2 Attack. Combo: +4 Attack instead','0');
INSERT INTO `CARTA` VALUES ('Conceal','Spell','Rogue','Classic','Common',NULL,'1',NULL,NULL,'Give your minions Stealth until your next turn','0');
INSERT INTO `CARTA` VALUES ('Defias Ringleader','Minion','Rogue','Classic','Common',NULL,'2','2','2','Combo: Summon a 2/1 Defias Bandit','0');
INSERT INTO `CARTA` VALUES ('Edwin VanCleef','Minion','Rogue','Classic','Legendary',NULL,'3','2','2','Combo: Gain +2/+2 for each card played earlier this turn','0');
INSERT INTO `CARTA` VALUES ('Eviscerate','Spell','Rogue','Classic','Common',NULL,'2',NULL,NULL,'Deal 2 damage. Combo: Deal 4 damage instead','0');
INSERT INTO `CARTA` VALUES ('Headcrack','Spell','Rogue','Classic','Rare',NULL,'2',NULL,NULL,'Deal 2 damage to the enemy hero. Combo: Return this to your hand next turn','0');
INSERT INTO `CARTA` VALUES ('Kidnapper','Minion','Rogue','Classic','Epic',NULL,'6','5','3','Combo: Return a minion to its owner''s hand','0');
INSERT INTO `CARTA` VALUES ('Master of Disguise','Minion','Rogue','Classic','Rare',NULL,'4','4','4','Battlecry: Give a friendly minion Stealth','0');
INSERT INTO `CARTA` VALUES ('Patient Assassin','Minion','Rogue','Classic','Epic',NULL,'2','1','1','Stealth. Destroy any minion damaged by this minion','0');
INSERT INTO `CARTA` VALUES ('Perdition''s Blade','Weapon','Rogue','Classic','Rare',NULL,'3','2','2','Battlecry: Deal 1 damage. Combo: Deal 2 damage instead','0');
INSERT INTO `CARTA` VALUES ('Preparation','Spell','Rogue','Classic','Epic',NULL,'0',NULL,NULL,'The next spell you cast this turn costs (3) less','0');
INSERT INTO `CARTA` VALUES ('Shadowstep','Spell','Rogue','Classic','Common',NULL,'0',NULL,NULL,'Return a friendly minion to your hand. It costs (2) less','0');
INSERT INTO `CARTA` VALUES ('SI-7 Agent','Minion','Rogue','Classic','Rare',NULL,'3','3','3','Combo: Deal 2 damage','0');
INSERT INTO `CARTA` VALUES ('Al''Akir the Windlord','Minion','Shaman','Classic','Legendary',NULL,'8','3','5','Windfury, Charge, Divine Shield, Taunt','0');
INSERT INTO `CARTA` VALUES ('Ancestral Spirit','Spell','Shaman','Classic','Rare',NULL,'2',NULL,NULL,'Give a minion Deathrattle: Resummon this minion','0');
INSERT INTO `CARTA` VALUES ('Doomhammer','Weapon','Shaman','Classic','Epic',NULL,'5','2','8','Windfury. Overload: (2)','0');
INSERT INTO `CARTA` VALUES ('Dust Devil','Minion','Shaman','Classic','Common',NULL,'1','3','1','Windfury. Overload: (2)','0');
INSERT INTO `CARTA` VALUES ('Earth Elemental','Minion','Shaman','Classic','Epic',NULL,'5','7','8','Taunt. Overload: (3)','0');
INSERT INTO `CARTA` VALUES ('Earth Shock','Spell','Shaman','Classic','Common',NULL,'1',NULL,NULL,'Silence a minion, then deal 1 damage to it','0');
INSERT INTO `CARTA` VALUES ('Far Sight','Spell','Shaman','Classic','Epic',NULL,'3',NULL,NULL,'Draw a card. That card costs (3) less','0');
INSERT INTO `CARTA` VALUES ('Feral Spirit','Spell','Shaman','Classic','Rare',NULL,'3',NULL,NULL,'Summon two 2/3 Spirit Wolves with Taunt. Overload: (2)','0');
INSERT INTO `CARTA` VALUES ('Forked Lightning','Spell','Shaman','Classic','Common',NULL,'1',NULL,NULL,'Deal 2 damage to 2 random enemy minions. Overload: (2)','0');
INSERT INTO `CARTA` VALUES ('Lava Burst','Spell','Shaman','Classic','Rare',NULL,'3',NULL,NULL,'Deal 5 damage. Overload: (2)','0');
INSERT INTO `CARTA` VALUES ('Lightning Bolt','Spell','Shaman','Classic','Common',NULL,'1',NULL,NULL,'Deal 3 damage. Overload: (1)','0');
INSERT INTO `CARTA` VALUES ('Lightning Storm','Spell','Shaman','Classic','Rare',NULL,'3',NULL,NULL,'Deal 2-3 damage to all enemy minions. Overload: (2)','0');
INSERT INTO `CARTA` VALUES ('Mana Tide Totem','Minion','Shaman','Classic','Rare',NULL,'3','0','3','At the end of your turn, draw a card','0');
INSERT INTO `CARTA` VALUES ('Stormforged Axe','Weapon','Shaman','Classic','Common',NULL,'2','2','3','Overload: (1)','0');
INSERT INTO `CARTA` VALUES ('Unbound Elemental','Minion','Shaman','Classic','Common',NULL,'3','2','4','Whenever you play a card with Overload, gain +1/+1','0');
INSERT INTO `CARTA` VALUES ('Bane of Doom','Spell','Warlock','Classic','Epic',NULL,'5',NULL,NULL,'Deal 2 damage to a character. If that kills it, summon a random Demon','0');
INSERT INTO `CARTA` VALUES ('Blood Imp','Minion','Warlock','Classic','Common','Demon','1','0','1','Stealth. At the end of your turn, give another random friendly minion +1 Health','0');
INSERT INTO `CARTA` VALUES ('Demonfire','Spell','Warlock','Classic','Common',NULL,'2',NULL,NULL,'Deal 2 damage to a minion. If it''s a friendly Demon, give it +2/+2 instead','0');
INSERT INTO `CARTA` VALUES ('Doomguard','Minion','Warlock','Classic','Rare','Demon','5','5','7','Charge. Battlecry: Discard two random cards','0');
INSERT INTO `CARTA` VALUES ('Felguard','Minion','Warlock','Classic','Rare','Demon','3','3','5','Taunt. Battlecry: Destroy one of your Mana Crystals','0');
INSERT INTO `CARTA` VALUES ('Flame Imp','Minion','Warlock','Classic','Common','Demon','1','3','2','Battlecry: Deal 3 damage to your hero','0');
INSERT INTO `CARTA` VALUES ('Lord Jaraxxus','Minion','Warlock','Classic','Legendary','Demon','9','3','15','Battlecry: Destroy your hero and replace it with Lord Jaraxxus','0');
INSERT INTO `CARTA` VALUES ('Pit Lord','Minion','Warlock','Classic','Epic','Demon','4','5','6','Battlecry: Deal 5 damage to your hero','0');
INSERT INTO `CARTA` VALUES ('Power Overwhelming','Spell','Warlock','Classic','Common',NULL,'1',NULL,NULL,'Give a friendly minion +4/+4 until end of turn. Then, it dies. Horribly','0');
INSERT INTO `CARTA` VALUES ('Sense Demons','Spell','Warlock','Classic','Common',NULL,'3',NULL,NULL,'Put 2 random Demons from you deck into your hand','0');
INSERT INTO `CARTA` VALUES ('Shadowflame','Spell','Warlock','Classic','Rare',NULL,'4',NULL,NULL,'Destroy a friendly minion and deal its Attack damage to all enemy minions','0');
INSERT INTO `CARTA` VALUES ('Siphon Soul','Spell','Warlock','Classic','Rare',NULL,'6',NULL,NULL,'Destroy a minion. Restore 3 Health to your hero','0');
INSERT INTO `CARTA` VALUES ('Summoning Portal','Minion','Warlock','Classic','Common',NULL,'4','0','4','Your minions costs (2) less, but not less than (1)','0');
INSERT INTO `CARTA` VALUES ('Twisting Nether','Spell','Warlock','Classic','Epic',NULL,'8',NULL,NULL,'Destroy all minions','0');
INSERT INTO `CARTA` VALUES ('Void Terror','Minion','Warlock','Classic','Rare','Demon','3','3','3','Battlecry: Destroy the minions on either side of this minion and gain their Attack and Health','0');
INSERT INTO `CARTA` VALUES ('Arathi Weaponsmith','Minion','Warrior','Classic','Common',NULL,'4','3','3','Battlecry: Equip a 2/2 weapon','0');
INSERT INTO `CARTA` VALUES ('Armorsmith','Minion','Warrior','Classic','Rare',NULL,'2','1','4','Whenever a friendly minion takes damage, gain 1 armor','0');
INSERT INTO `CARTA` VALUES ('Battle Rage','Spell','Warrior','Classic','Common',NULL,'2',NULL,NULL,'Draw a card for each damaged friendly character','0');
INSERT INTO `CARTA` VALUES ('Brawl','Spell','Warrior','Classic','Epic',NULL,'5',NULL,NULL,'Destroy all minions except one. (chosen randomly)','0');
INSERT INTO `CARTA` VALUES ('Commanding Shout','Spell','Warrior','Classic','Rare',NULL,'2',NULL,NULL,'Your minions can''t be reduced below 1 Health this turn. Draw a card','0');
INSERT INTO `CARTA` VALUES ('Cruel Taskmaster','Minion','Warrior','Classic','Common',NULL,'2','2','2','Battlecry: Deal 1 damage to a minion and give it +2 Attack','0');
INSERT INTO `CARTA` VALUES ('Frothing Berserker','Minion','Warrior','Classic','Rare',NULL,'3','2','4','Whenever a minion takes damage, gain +1 Attack','0');
INSERT INTO `CARTA` VALUES ('Gorehowl','Weapon','Warrior','Classic','Epic',NULL,'7','7','1','Attacking a minion costs 1 Attack instead of 1 Durability','0');
INSERT INTO `CARTA` VALUES ('Grommash Hellscream','Minion','Warrior','Classic','Legendary',NULL,'8','4','9','Charge. Enrage: +6 Attack','0');
INSERT INTO `CARTA` VALUES ('Inner Rage','Spell','Warrior','Classic','Common',NULL,'0',NULL,NULL,'Deal 1 damage to a minion and give it +2 Attack','0');
INSERT INTO `CARTA` VALUES ('Mortal Strike','Spell','Warrior','Classic','Rare',NULL,'4',NULL,NULL,'Deal 4 damage. If you have 12 or less Health, deal 6 instead','0');
INSERT INTO `CARTA` VALUES ('Rampage','Spell','Warrior','Classic','Common',NULL,'2',NULL,NULL,'Give a damaged minion +3/+3','0');
INSERT INTO `CARTA` VALUES ('Shield Slam','Spell','Warrior','Classic','Epic',NULL,'1',NULL,NULL,'Deal 1 damage to a minion for each Armor you have','0');
INSERT INTO `CARTA` VALUES ('Slam','Spell','Warrior','Classic','Common',NULL,'2',NULL,NULL,'Deal 2 damage to a minion. If it survives, draw a card','0');
INSERT INTO `CARTA` VALUES ('Upgrade!','Spell','Warrior','Classic','Rare',NULL,'1',NULL,NULL,'If you have a weapon, give it +1/+1. Otherwise equip a 1/3 weapon','0');
INSERT INTO `CARTA` VALUES ('Baron Rivendare','Minion','Neutral','Naxxramas','Legendary',NULL,'4','1','7','Your minions trigger their Deathrattles twice','0');
INSERT INTO `CARTA` VALUES ('Dancing Swords','Minion','Neutral','Naxxramas','Common',NULL,'3','4','4','Deathrattle: Your opponent draws a card','0');
INSERT INTO `CARTA` VALUES ('Deathlord','Minion','Neutral','Naxxramas','Rare',NULL,'3','2','8','Taunt. Deathrattle: Your opponent puts a minion from their deck into the battlefield','0');
INSERT INTO `CARTA` VALUES ('Echoing Ooze','Minion','Neutral','Naxxramas','Epic',NULL,'2','1','2','Battlecry: Summon an exact copy of this minion at the end of the turn','0');
INSERT INTO `CARTA` VALUES ('Feugen','Minion','Neutral','Naxxramas','Legendary',NULL,'5','4','7','Deathrattle: If Stalagg also died this game, summon Thaddius','0');
INSERT INTO `CARTA` VALUES ('Haunted Creeper','Minion','Neutral','Naxxramas','Common',NULL,'2','1','2','Deathrattle: Summon two 1/1 Spectral Spiders','0');
INSERT INTO `CARTA` VALUES ('Kel''Thuzad','Minion','Neutral','Naxxramas','Legendary',NULL,'8','6','8','At the end of each turn, summon al friendly minions that died this turn','0');
INSERT INTO `CARTA` VALUES ('Loatheb','Minion','Neutral','Naxxramas','Legendary',NULL,'5','5','5','Battlecry: Enemy spells cost (5) more next turn','0');
INSERT INTO `CARTA` VALUES ('Mad Scientist','Minion','Neutral','Naxxramas','Common',NULL,'2','2','2','Deathrattle: Put a Secret from your deck into the battlefield','0');
INSERT INTO `CARTA` VALUES ('Maexxna','Minion','Neutral','Naxxramas','Legendary',NULL,'6','2','8','Destroy any minion damaged by this minion','0');
INSERT INTO `CARTA` VALUES ('Nerub''ar Weblord','Minion','Neutral','Naxxramas','Common',NULL,'2','1','4','Minions with Battlecry cost (2) more','0');
INSERT INTO `CARTA` VALUES ('Nerubian Egg','Minion','Neutral','Naxxramas','Rare',NULL,'2','0','2','Deathrattle: Summon a 4/4 nerubian','0');
INSERT INTO `CARTA` VALUES ('Shade of Naxxramas','Minion','Neutral','Naxxramas','Epic',NULL,'3','2','2','Stealth. At the start of your turn, gain +1/+1','0');
INSERT INTO `CARTA` VALUES ('Sludge Belcher','Minion','Neutral','Naxxramas','Rare',NULL,'5','3','5','Taunt. Deathrattle: Summon a 1/2 Slime with Taunt','0');
INSERT INTO `CARTA` VALUES ('Spectral Knight','Minion','Neutral','Naxxramas','Common',NULL,'5','4','6','Can''t be targeted by spells or Hero Powers','0');
INSERT INTO `CARTA` VALUES ('Stalagg','Minion','Neutral','Naxxramas','Legendary',NULL,'5','7','4','Deathrattle: If Feugen also died this game, summon Thaddius','0');
INSERT INTO `CARTA` VALUES ('Stoneskin Gargoyle','Minion','Neutral','Naxxramas','Common',NULL,'3','1','4','At the start of your turn, restore this minion to full Health','0');
INSERT INTO `CARTA` VALUES ('Undertaker','Minion','Neutral','Naxxramas','Common',NULL,'1','1','2','Whenever you summon a minion with Deathrattle, gain +1/+1','0');
INSERT INTO `CARTA` VALUES ('Unstable Ghoul','Minion','Neutral','Naxxramas','Common',NULL,'2','1','3','Taunt. Deathrattle: Deal 1 damage to all minions','0');
INSERT INTO `CARTA` VALUES ('Wailing Soul','Minion','Neutral','Naxxramas','Rare',NULL,'4','3','5','Battlecry: Silence your other minions','0');
INSERT INTO `CARTA` VALUES ('Zombie Chow','Minion','Neutral','Naxxramas','Common',NULL,'1','2','3','Deathrattle: Restore 5 Health to the enemy hero','0');
INSERT INTO `CARTA` VALUES ('Poison Seeds','Spell','Druid','Naxxramas','Common',NULL,'4',NULL,NULL,'Destroy all minions and summon 2/2 Treants to replace them','0');
INSERT INTO `CARTA` VALUES ('Webspinner','Minion','Hunter','Naxxramas','Common','Beast','1','1','1','Deathrattle: Add a random Beast card to your hand','0');
INSERT INTO `CARTA` VALUES ('Duplicate','Spell','Mage','Naxxramas','Common',NULL,'3',NULL,NULL,'Secret: When a friendly minion dies, put 2 copies of it into your hand','0');
INSERT INTO `CARTA` VALUES ('Avenge','Spell','Paladin','Naxxramas','Common',NULL,'1',NULL,NULL,'Secret: When one of your minions dies, give a random friendly minion +3/+2','0');
INSERT INTO `CARTA` VALUES ('Dark Cultist','Minion','Priest','Naxxramas','Common',NULL,'3','3','4','Deathrattle: Give a friendly minion +3 Health','0');
INSERT INTO `CARTA` VALUES ('Anub''ar Ambusher','Minion','Rogue','Naxxramas','Common',NULL,'4','5','5','Deathrattle: Return a random friendly minion to your hand','0');
INSERT INTO `CARTA` VALUES ('Reincarnate','Spell','Shaman','Naxxramas','Common',NULL,'2',NULL,NULL,'Destroy a minion, then return it to life with full Health','0');
INSERT INTO `CARTA` VALUES ('Voidcaller','Minion','Warlock','Naxxramas','Common','Demon','4','3','4','Deathrattle: Put a random Demon from your hand into the battlefield','0');
INSERT INTO `CARTA` VALUES ('Death''s Bite','Weapon','Warrior','Naxxramas','Common',NULL,'4','4','2','Deathrattle: Deal 1 damage to all minions','0');
