BEGIN TRANSACTION;
CREATE TABLE "SQLiteCartas" (
	`Nombre`	TEXT,
	`Clave`	TEXT,
	`Tipo`	TEXT,
	`Clase`	TEXT,
	`Set`	TEXT,
	`Rareza`	TEXT,
	`Tag`	TEXT,
	`Coste`	INTEGER,
	`Ataque`	INTEGER,
	`Salud`	INTEGER,
	`Descripción`	TEXT,
	`Nºdecopias`	INTEGER
);
INSERT INTO `SQLiteCartas` VALUES ('Ancient of Lore','c1','Minion','Druid','Classic','Epic',NULL,'7','5','5','Choose One - Draw 2 cards; or Restore 5 Heath',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ancient of War','c2','Minion','Druid','Classic','Epic',NULL,'7','5','5','Choose One - +5 Attack; or +5 Health and Taunt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Anodized Robo Cub','c3','Minion','Druid','Goblins Vs Gnomes','Common','Mech','2','2','2','Taunt. Choose One - +1 Attack; or +1 Health',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Bite','c4','Spell','Druid','Classic','Rare',NULL,'4',NULL,NULL,'Give your Hero +4 Attack this turn and 4 Armor',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Cenarius','c5','Minion','Druid','Classic','Legendary',NULL,'9','5','8','Choose One - Give your other minions +2/+2; or summon two 2/2 Treants with Taunt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Claw','c6','Spell','Druid','Basic','Basic',NULL,'1',NULL,NULL,'Give your hero +2 Attack this turn and +2 Armor','2');
INSERT INTO `SQLiteCartas` VALUES ('Dark Wispers','c7','Spell','Druid','Goblins Vs Gnomes','Epic',NULL,'6',NULL,NULL,'Choose One - Summon 5 Wisps; or Give a minion +5/+5 and Taunt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Druid of the Claw','c8','Minion','Druid','Classic','Common',NULL,'5','4','4','Choose One - Charge; or +2 Health and Taunt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Druid of the Fang','c9','Minion','Druid','Goblins Vs Gnomes','Common',NULL,'5','4','4','Battlecry: If you have a Beast, transform this minion into a 7/7',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Force of Nature','c10','Spell','Druid','Classic','Epic',NULL,'6',NULL,NULL,'Summon three 2/2 Treants with Charge that die at the end of the turn',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Grove Tender','c11','Minion','Druid','Goblins Vs Gnomes','Rare',NULL,'3','2','4','Choose One - Give each player a Mana Crystal; or Each player draws a card',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Healing Touch','c12','Spell','Druid','Basic','Basic',NULL,'3',NULL,NULL,'Restore 8 Health','2');
INSERT INTO `SQLiteCartas` VALUES ('Innervate','c13','Spell','Druid','Basic','Basic',NULL,'0',NULL,NULL,'Gain 2 Mana Crystals this turn only','2');
INSERT INTO `SQLiteCartas` VALUES ('Ironbark Protector','c14','Minion','Druid','Basic','Basic',NULL,'8','8','8','Taunt','2');
INSERT INTO `SQLiteCartas` VALUES ('Keeper of the Grove','c15','Minion','Druid','Classic','Rare',NULL,'4','2','4','Choose One - Deal 2 Damage; or Silence a minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Malorne','c16','Minion','Druid','Goblins Vs Gnomes','Legendary','Beast','7','9','7','Deathrattle: Shuffle this minion into your deck',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mark of Nature','c17','Spell','Druid','Classic','Common',NULL,'3',NULL,NULL,'Choose One - Give a minion +4; or +4 Health and Taunt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mark of the Wild','c18','Spell','Druid','Basic','Basic',NULL,'2',NULL,NULL,'Give a minion Taunt and +2/+2 (+2 Attack/+2 Health)','2');
INSERT INTO `SQLiteCartas` VALUES ('Mech-Bear-Cat','c19','Minion','Druid','Goblins Vs Gnomes','Rare','Mech','6','7','6','Whenever this minion takes damage, add a Spare Part card to your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Moonfire','c20','Spell','Druid','Basic','Basic',NULL,'0',NULL,NULL,'Deal 1 damage','2');
INSERT INTO `SQLiteCartas` VALUES ('Naturalize','c21','Spell','Druid','Classic','Common',NULL,'1',NULL,NULL,'Destroy a minion. Your opponent draws 2 cards',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Nourish','c22','Spell','Druid','Classic','Rare',NULL,'5',NULL,NULL,'Choose One - Gain 2 Mana Crystals; or Draw 3 cards',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Poison Seeds','c23','Spell','Druid','Naxxramas','Common',NULL,'4',NULL,NULL,'Destroy all minions and summon 2/2 Treants to replace them',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Power of the Wild','c24','Spell','Druid','Classic','Common',NULL,'2',NULL,NULL,'Choose One - Give your minions +1/+1; or Summon a 3/2 Panther',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Recycle','c25','Spell','Druid','Goblins Vs Gnomes','Rare',NULL,'6',NULL,NULL,'Shuffle an enemy minion into your opponent''s deck',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Savage Roar','c26','Spell','Druid','Basic','Basic',NULL,'3',NULL,NULL,'Give your characters +2 Attack this turn','2');
INSERT INTO `SQLiteCartas` VALUES ('Savagery','c27','Spell','Druid','Classic','Rare',NULL,'1',NULL,NULL,'Deal damage equal to your hero''s Attack to a minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Soul of the Forest','c28','Spell','Druid','Classic','Common',NULL,'4',NULL,NULL,'Give your minions Deathrattle: Summon a 2/2 Treant',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Starfall','c29','Spell','Druid','Classic','Rare',NULL,'5',NULL,NULL,'Choose One - Deal 5 damge to a minion; or 2 damage to all enemy minions',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Starfire','c30','Spell','Druid','Basic','Basic',NULL,'6',NULL,NULL,'Deal 5 damage. Draw a card','2');
INSERT INTO `SQLiteCartas` VALUES ('Swipe','c31','Spell','Druid','Basic','Basic',NULL,'4',NULL,NULL,'Deal 4 damage to an enemy and 1 damage to all other enemies','2');
INSERT INTO `SQLiteCartas` VALUES ('Tree of Life','c32','Spell','Druid','Goblins Vs Gnomes','Epic',NULL,'9',NULL,NULL,'Restore all characters to full Health',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Wild Growth','c33','Spell','Druid','Basic','Basic',NULL,'2',NULL,NULL,'Gain an empty Mana Crystal','2');
INSERT INTO `SQLiteCartas` VALUES ('Wrath','c34','Spell','Druid','Classic','Common',NULL,'2',NULL,NULL,'Choose One - Deal 3 damage to a minion; or deal 1 damage and draw a card',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Animal Companion','c35','Spell','Hunter','Basic','Basic',NULL,'3',NULL,NULL,'Summon a random Beast Companion','2');
INSERT INTO `SQLiteCartas` VALUES ('Arcane Shot','c36','Spell','Hunter','Basic','Basic',NULL,'1',NULL,NULL,'Deal 2 damage','2');
INSERT INTO `SQLiteCartas` VALUES ('Bestial Wrath','c37','Spell','Hunter','Classic','Epic',NULL,'1',NULL,NULL,'Give a Beast +2 Attack and Inmune this turn',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Call Pet','c38','Spell','Hunter','Goblins Vs Gnomes','Rare',NULL,'2',NULL,NULL,'Draw a card. If it''s a Beast, it costs (4) less',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Cobra Shot','c39','Spell','Hunter','Goblins Vs Gnomes','Common',NULL,'5',NULL,NULL,'Deal 3 damage to a minion and the enemy hero',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Deadly Shot','c40','Spell','Hunter','Classic','Common',NULL,'3',NULL,NULL,'Destroy a random enemy minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Eaglehorn Bow','c41','Weapon','Hunter','Classic','Rare',NULL,'3','3','2','Whenever a friendly secret is revealed, gain +1 Durability',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Explosive Shot','c42','Spell','Hunter','Classic','Rare',NULL,'5',NULL,NULL,'Deal 5 damage to a minion and 2 damage to adjacent ones',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Explosive Trap','c43','Spell','Hunter','Classic','Common',NULL,'2',NULL,NULL,'Secret: When your hero is attacked, deal 2 damage to all enemies',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Feign Death','c44','Spell','Hunter','Goblins Vs Gnomes','Epic',NULL,'2',NULL,NULL,'Trigger all Deathrattles on your minions',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Flare','c45','Spell','Hunter','Classic','Rare',NULL,'2',NULL,NULL,'All minions lose Stelath. Destroy all enemy Secrets. Draw a card',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Freezing Trap','c46','Spell','Hunter','Classic','Common',NULL,'2',NULL,NULL,'Secret: When an enmy minion attacks, return it to its owner''s hand and it costs (2) more',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Gahz''rilla','c47','Minion','Hunter','Goblins Vs Gnomes','Legendary','Beast','7','6','9','Whenever this minion takes damage, double its Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Gladiator''s Longbow','c48','Weapon','Hunter','Classic','Epic',NULL,'7','5','2','Your hero is Inmune while attacking',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Glaivezooka','c49','Weapon','Hunter','Goblins Vs Gnomes','Common',NULL,'2',NULL,NULL,'Battlecry: Give a random friendly minion +1 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Houndmaster','c50','Minion','Hunter','Basic','Basic',NULL,'4',NULL,NULL,'Battlecry: Give a friendly Beast +2/+2 and Taunt','2');
INSERT INTO `SQLiteCartas` VALUES ('Hunter''s Mark','c51','Spell','Hunter','Basic','Basic',NULL,'0',NULL,NULL,'Change a minion''s health to 1','2');
INSERT INTO `SQLiteCartas` VALUES ('Kill Command','c52','Spell','Hunter','Basic','Basic',NULL,'3',NULL,NULL,'Deal 3 damage. If you control a Beast, deal 5 damage instead','2');
INSERT INTO `SQLiteCartas` VALUES ('King Krush','c53','Minion','Hunter','Classic','Legendary','Beast','9','8','8','Charge',NULL);
INSERT INTO `SQLiteCartas` VALUES ('King of Beasts','c54','Minion','Hunter','Goblins Vs Gnomes','Rare','Beast','5','2','6','Taunt. Battlecry: Gain +1 Attack for each other Beast you have',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Metaltooth Leaper','c55','Minion','Hunter','Goblins Vs Gnomes','Rare','Mech','3','3','3','Battlecry: Give your other Mechs +2 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Misdirection','c56','Spell','Hunter','Classic','Rare',NULL,'2',NULL,NULL,'Secret: When a character attacks your hero, instead he attacks another random character',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Multi-Shot','c57','Spell','Hunter','Basic','Basic',NULL,'4',NULL,NULL,'Deal 3 damage to two random enemy minions','2');
INSERT INTO `SQLiteCartas` VALUES ('Savannah Highmane','c58','Minion','Hunter','Classic','Rare','Beast','6','6','5','Deathrattle: Summon two 2/2 Hyenas',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Scavenging Hyena','c59','Minion','Hunter','Classic','Common','Beast','2','2','2','Whenever a friendly Beast dies, gain +2/+1',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Snake Trap','c60','Spell','Hunter','Classic','Epic',NULL,'2',NULL,NULL,'Secret: When one of your minions is attacked, summon three 1/1 Snakes',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Snipe','c61','Spell','Hunter','Classic','Common',NULL,'2',NULL,NULL,'Secret: When your opponent plays a minion, deal 4 damage to it',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Starving Buzzard','c62','Minion','Hunter','Basic','Basic','Beast','5','3','2','Whenever you summon a Beast, draw a card','2');
INSERT INTO `SQLiteCartas` VALUES ('Steamwheedle Sniper','c63','Minion','Hunter','Goblins Vs Gnomes','Epic',NULL,'2','2','3','Your Hero Power can target minions',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Timber Wolf','c64','Minion','Hunter','Basic','Basic','Beast','1','1','1','Your other Beasts have +1 Attack','2');
INSERT INTO `SQLiteCartas` VALUES ('Tracking','c65','Spell','Hunter','Basic','Basic',NULL,'1',NULL,NULL,'Look at the top three cards of your deck. Draw one and discard the others','2');
INSERT INTO `SQLiteCartas` VALUES ('Tundra Rhino','c66','Minion','Hunter','Basic','Basic','Beast','5','2','5','Your Beasts have Charge','2');
INSERT INTO `SQLiteCartas` VALUES ('Unleash the Hounds','c67','Spell','Hunter','Classic','Common',NULL,'3',NULL,NULL,'For each enemy minion, summon a 1/1 Hound with Charge',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Webspinner','c68','Minion','Hunter','Naxxramas','Common','Beast','1','1','1','Deathrattle: Add a random Beast card to your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Arcane Explosion','c69','Spell','Mage','Basic','Basic',NULL,'2',NULL,NULL,'Deal 1 damage to all enemy minions','2');
INSERT INTO `SQLiteCartas` VALUES ('Arcane Intellect','c70','Spell','Mage','Basic','Basic',NULL,'3',NULL,NULL,'Draw 2 cards','2');
INSERT INTO `SQLiteCartas` VALUES ('Arcane Missiles','c71','Spell','Mage','Basic','Basic',NULL,'1',NULL,NULL,'Deal 3 damage randomly split among enemy characters','2');
INSERT INTO `SQLiteCartas` VALUES ('Archmage Antonidas','c72','Minion','Mage','Classic','Legendary',NULL,'7','5','7','Whenever you cast a spell, add a ''Fireball'' spell to your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Blizzard','c73','Spell','Mage','Classic','Rare',NULL,'6',NULL,NULL,'Deal 2 damage to all enemy minions and Freeze them',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Cone of Cold','c74','Spell','Mage','Classic','Common',NULL,'4',NULL,NULL,'Freeze a minion and the minions next to it, and deal 1 damage to them',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Counterspell','c75','Spell','Mage','Classic','Rare',NULL,'3',NULL,NULL,'Secret: When your opponent casts a spell, Counter it',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Duplicate','c76','Spell','Mage','Naxxramas','Common',NULL,'3',NULL,NULL,'Secret: When a friendly minion dies, put 2 copies of it into your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Echo of Medivh','c77','Spell','Mage','Goblins Vs Gnomes','Epic',NULL,'4',NULL,NULL,'Put a copy of each friendly minion into your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ethereal Arcanist','c78','Minion','Mage','Classic','Rare',NULL,'4','3','3','If you control a Secret at the end of the turn, gain +2/+2',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Fireball','c79','Spell','Mage','Basic','Basic',NULL,'4',NULL,NULL,'Deal 6 damage','2');
INSERT INTO `SQLiteCartas` VALUES ('Flame Leviathan','c80','Minion','Mage','Goblins Vs Gnomes','Legendary','Mech','7','7','7','When you draw this, deal 2 damage to all characters',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Flamecannon','c81','Spell','Mage','Goblins Vs Gnomes','Common',NULL,'2',NULL,NULL,'Deal 4 damage to a random enemy minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Flamestrike','c82','Spell','Mage','Basic','Basic',NULL,'7',NULL,NULL,'Deal 4 damage to all enemy minions','2');
INSERT INTO `SQLiteCartas` VALUES ('Frost Nova','c83','Spell','Mage','Basic','Basic',NULL,'3',NULL,NULL,'Freeze all enemy minions','2');
INSERT INTO `SQLiteCartas` VALUES ('Frostbolt','c84','Spell','Mage','Basic','Basic',NULL,'2',NULL,NULL,'Deal 3 damage to a character and Freeze it','2');
INSERT INTO `SQLiteCartas` VALUES ('Goblin Blastmage','c85','Minion','Mage','Goblins Vs Gnomes','Rare',NULL,'4','5','4','Battlecry: If you have a Mech, deal 4 damage randomly split among all enemies',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ice Barrier','c86','Spell','Mage','Classic','Common',NULL,'3',NULL,NULL,'Secret: When your hero is attacked, gain 8 Armor',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ice Block','c87','Spell','Mage','Classic','Epic',NULL,'3',NULL,NULL,'Secret: When your hero takes fatal damage, prevent it and become Inmune this turn',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ice Lance','c88','Spell','Mage','Classic','Common',NULL,'1',NULL,NULL,'Freeze a Character. If it was already Frozen, deal 4 damage instead',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Kirin Tor Mage','c89','Minion','Mage','Classic','Rare',NULL,'3','4','3','Battlecry: The next secret you play this turn costs (0)',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mana Wyrm','c90','Minion','Mage','Classic','Common',NULL,'1','1','3','Whenever you cast a spell, gain +1 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mirror Entity','c91','Spell','Mage','Classic','Common',NULL,'3',NULL,NULL,'Secret: When your opponent plays a minion, summon a copy of it',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mirror Image','c92','Spell','Mage','Basic','Basic',NULL,'1',NULL,NULL,'Summon two 0/2 minions with Taunt','2');
INSERT INTO `SQLiteCartas` VALUES ('Polymorph','c93','Spell','Mage','Basic','Basic',NULL,'4',NULL,NULL,'Transform a minion into a 1/1 Sheep','2');
INSERT INTO `SQLiteCartas` VALUES ('Pyroblast','c94','Spell','Mage','Classic','Epic',NULL,'10',NULL,NULL,'Deal 10 damage',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Snowchugger','c95','Minion','Mage','Goblins Vs Gnomes','Common','Mech','2','2','3','Freeze any character damaged by this minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Soot Spewer','c96','Minion','Mage','Goblins Vs Gnomes','Rare','Mech','3','3','3','Spell Damage +1',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Sorcerer''s Apprentice','c97','Minion','Mage','Classic','Common',NULL,'2','3','2','Your spells costs (1) less',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Spellbender','c98','Spell','Mage','Classic','Epic',NULL,'3',NULL,NULL,'Secret: When an enemy casts a spell on a minion, summon a 1/3 as the new target',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Unstable Portal','c99','Spell','Mage','Goblins Vs Gnomes','Rare',NULL,'2',NULL,NULL,'Add a random minion to your hand. It costs (3) less',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Vaporize','c100','Spell','Mage','Classic','Rare',NULL,'3',NULL,NULL,'Secret: When a minion attacks your hero, destroy it',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Water Elemental','c101','Minion','Mage','Basic','Basic',NULL,'4','3','6','Freeze any character damaged by this minion','2');
INSERT INTO `SQLiteCartas` VALUES ('Wee Spellstopper','c102','Minion','Mage','Goblins Vs Gnomes','Epic',NULL,'4','2','5','Adjacent minions can''t be targeted by spells or Hero Powers',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Abomination','c103','Minion','Neutral','Classic','Rare',NULL,'5','4','4','Taunt. Deathrattle: Deal 2 damage to ALL characters',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Abusive Sergeant','c104','Minion','Neutral','Classic','Common',NULL,'1','2','1','Battlecry: Give a minion +2 Attack this turn',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Acidic Swamp Ooze','c105','Minion','Neutral','Basic','Basic',NULL,'2','3','2','Battlecry: Destroy your opponent''s weapon','2');
INSERT INTO `SQLiteCartas` VALUES ('Acolyte of Pain','c106','Minion','Neutral','Classic','Common',NULL,'3','1','3','Whenever this minion takes damage, draw a card',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Alarm-o-Bot','c107','Minion','Neutral','Classic','Rare','Mech','3','0','3','At the start of your turn, swap this minion with a random one in your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Alexstrasza','c108','Minion','Neutral','Classic','Legendary','Dragon','9','8','8','Battlecry: Set a hero''s remaining Health to 15',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Amani Berserker','c109','Minion','Neutral','Classic','Common',NULL,'2','2','3','Enrage: +3 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ancient Brewmaster','c110','Minion','Neutral','Classic','Common',NULL,'4','5','4','Battlecry: Return a friendly minion from the battlefield to your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ancient Mage','c111','Minion','Neutral','Classic','Rare',NULL,'4','2','5','Battlecry: Give adjacent minions +1 Spell Damage',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ancient Watcher','c112','Minion','Neutral','Classic','Rare',NULL,'2','4','5','Can''t Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Angry Chicken','c113','Minion','Neutral','Classic','Rare','Beast','1','1','1','Enrage: +5 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Annoy-o-Tron','c114','Minion','Neutral','Goblins Vs Gnomes','Common','Mech','2','1','2','Taunt. Divine Shield',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Antique Healbot','c115','Minion','Neutral','Goblins Vs Gnomes','Common','Mech','5','3','3','Battlecry: Restore 8 Health to your hero',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Arcane Golem','c116','Minion','Neutral','Classic','Rare',NULL,'3','4','2','Charge. Battlecry: Give your opponent a Mana Crystal',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Arcane Nullifier X-21','c117','Minion','Neutral','Goblins Vs Gnomes','Rare','Mech','4','2','5','Taunt. Can''t be targeted by spells or Hero Powers',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Archmage','c118','Minion','Neutral','Basic','Basic',NULL,'6','4','7','Spell Damage +1','2');
INSERT INTO `SQLiteCartas` VALUES ('Argent Commander','c119','Minion','Neutral','Classic','Rare',NULL,'6','4','2','Charge, Divine Shield',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Argent Squire','c120','Minion','Neutral','Classic','Common',NULL,'1','1','1','Divine Shield',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Azure Drake','c121','Minion','Neutral','Classic','Rare','Dragon','5','4','4','Spell Damage +1, Battlecry: Draw a card',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Baron Geddon','c122','Minion','Neutral','Classic','Legendary',NULL,'7','7','5','At the end of your turn, deal 2 damage to ALL other characters',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Baron Rivendare','c123','Minion','Neutral','Naxxramas','Legendary',NULL,'4','1','7','Your minions trigger their Deathrattles twice',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Big Game Hunter','c124','Minion','Neutral','Classic','Epic',NULL,'3','4','2','Battlecry: Destroy a minion with an Attack of 7 or more',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Blingtron 3000','c125','Minion','Neutral','Goblins Vs Gnomes','Legendary','Mech','5','3','4','Battlecry: Equip a random weapon for each player',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Blood Knight','c126','Minion','Neutral','Classic','Epic',NULL,'3','3','3','Battlecry: All minios lose Divine Shield. Gain +3/+3 for each Shield lost',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Bloodfen Raptor','c127','Minion','Neutral','Basic','Basic','Beast','2','3','2',NULL,'2');
INSERT INTO `SQLiteCartas` VALUES ('Bloodmage Thalnos','c128','Minion','Neutral','Classic','Legendary',NULL,'2','1','1','Spell Damage +1, Deathrattle: Draw a card',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Bloodsail Corsair','c129','Minion','Neutral','Classic','Rare','Pirate','1','1','2','Battlecry: Remove 1 Durability from your opponent''s weapon',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Bloodsail Raider','c130','Minion','Neutral','Classic','Common','Pirate','2','2','3','Battlecry: Gain attack equal to the Attack of your weapon',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Bluegill Warrior','c131','Minion','Neutral','Basic','Basic','Murloc','2','2','1','Charge','2');
INSERT INTO `SQLiteCartas` VALUES ('Bomb Lobber','c132','Minion','Neutral','Goblins Vs Gnomes','Rare',NULL,'5','3','3','Battlecry: Deal 4 damage to a random enemy minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Booty Bay Bodyguard','c133','Minion','Neutral','Basic','Basic',NULL,'5','5','4','Taunt','2');
INSERT INTO `SQLiteCartas` VALUES ('Boulderfist Ogre','c134','Minion','Neutral','Basic','Basic',NULL,'6','6','7',NULL,'2');
INSERT INTO `SQLiteCartas` VALUES ('Burly Rockjaw Trogg','c135','Minion','Neutral','Goblins Vs Gnomes','Common',NULL,'4','3','5','Whenever your opponent casts a spell, gain +2 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Cairne Bloodhoof','c136','Minion','Neutral','Classic','Legendary',NULL,'6','4','5','Deathrattle: Summon a 4/5 Baine Bloodhoof',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Captain Greenskin','c137','Minion','Neutral','Classic','Legendary','Pirate','5','5','4','Battlecry: Give your weapon +1/+1',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Captain''s Parrot','c138','Minion','Neutral','Promo','Epic','Beast','2','1','1','Battlecry: Put a random Pirate from your deck into your hand.',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Chillwind Yeti','c139','Minion','Neutral','Basic','Basic',NULL,'4','4','5',NULL,'2');
INSERT INTO `SQLiteCartas` VALUES ('Clockwork Giant','c140','Minion','Neutral','Goblins Vs Gnomes','Epic','Mech','12','8','8','Costs (1) less for each card in your opponent''s hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Clockwork Gnome','c141','Minion','Neutral','Goblins Vs Gnomes','Common','Mech','1','2','1','Deathrattle: Add a Spare Part card to your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Cogmaster','c142','Minion','Neutral','Goblins Vs Gnomes','Common',NULL,'1','1','2','Has +2 Attack while you have a Mech',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Coldlight Oracle','c143','Minion','Neutral','Classic','Rare','Murloc','3','2','2','Battlecry: Each player draws 2 cards',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Coldlight Seer','c144','Minion','Neutral','Classic','Rare','Murloc','3','2','3','Battlecry: Give ALL other Murlocs +2 Health',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Core Hound','c145','Minion','Neutral','Basic','Basic','Beast','7','9','5',NULL,'2');
INSERT INTO `SQLiteCartas` VALUES ('Crazed Alchemist','c146','Minion','Neutral','Classic','Rare',NULL,'2','2','2','Battlecry: Swap the Attack and Health of a minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Cult Master','c147','Minion','Neutral','Classic','Common',NULL,'4','4','2','Whenever one of your other minions die, draw a card',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Dalaran Mage','c148','Minion','Neutral','Basic','Basic',NULL,'3','1','4','Spell Damage +1','2');
INSERT INTO `SQLiteCartas` VALUES ('Dancing Swords','c149','Minion','Neutral','Naxxramas','Common',NULL,'3','4','4','Deathrattle: Your opponent draws a card',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Dark Iron Dwarf','c150','Minion','Neutral','Classic','Common',NULL,'4','4','4','Battlecry: Give a minion +2 Attack this turn',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Darkscale Healer','c151','Minion','Neutral','Basic','Basic',NULL,'5','4','5','Battlecry: Restore 2 Health to all friendly characters','2');
INSERT INTO `SQLiteCartas` VALUES ('Deathlord','c152','Minion','Neutral','Naxxramas','Rare',NULL,'3','2','8','Taunt. Deathrattle: Your opponent puts a minion from their deck into the battlefield',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Deathwing','c153','Minion','Neutral','Classic','Legendary','Dragon','10','12','12','Battlecry: Destroy all other minions and discard your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Defender of Argus','c154','Minion','Neutral','Classic','Rare',NULL,'4','2','3','Battlecry: Give adjacent minions +1/+1 and Taunt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Demolisher','c155','Minion','Neutral','Classic','Rare','Mech','3','1','4','At the start of your turn, deal 2 damage to a random enemy',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Dire Wolf Alpha','c156','Minion','Neutral','Classic','Common','Beast','2','2','2','Adjacent minions have +1 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Doomsayer','c157','Minion','Neutral','Classic','Epic',NULL,'2','0','7','At the start of your turn, destroy ALL minions',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Dr. Boom','c158','Minion','Neutral','Goblins Vs Gnomes','Legendary',NULL,'7','7','7','Battlecry: Summon two 1/1 Boom Bots. WARNING: Bots may explode',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Dragonling Mechanic','c159','Minion','Neutral','Basic','Basic',NULL,'4','2','4','Battlecry: Summon a 2/1 Mechanical Dragonling','2');
INSERT INTO `SQLiteCartas` VALUES ('Dread Corsair','c160','Minion','Neutral','Classic','Common','Pirate','4','3','3','Taunt. Costs (1) less per Attack of your weapon',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Earthen Ring Farseer','c161','Minion','Neutral','Classic','Common',NULL,'3','3','3','Battlecry: Restore 3 Health',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Echoing Ooze','c162','Minion','Neutral','Naxxramas','Epic',NULL,'2','1','2','Battlecry: Summon an exact copy of this minion at the end of the turn',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Elite Tauren Chieftain','c163','Minion','Neutral','Promo','Legendary',NULL,'5','5','5','Battlecry: Give both players the power to ROCK! (with a Power Chord card)',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Elven Archer','c164','Minion','Neutral','Basic','Basic',NULL,'1','1','1','Battlecry: Deal 1 damage','2');
INSERT INTO `SQLiteCartas` VALUES ('Emperor Cobra','c165','Minion','Neutral','Classic','Rare','Beast','3','2','3','Destroy any minion damaged by this minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Enhace-o Mechano','c166','Minion','Neutral','Goblins Vs Gnomes','Epic','Mech','4','3','2','Battlecry: Give your other minions Windfury, Taunt or Divine Shield (at random)',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Explosive Sheep','c167','Minion','Neutral','Goblins Vs Gnomes','Common','Mech','2','1','1','Deathrattle: Deal 2 damage to all minions',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Faceless Manipulator','c168','Minion','Neutral','Classic','Epic',NULL,'5','3','3','Battlecry: Choose a minion and become a copy of it',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Faerie Dragon','c169','Minion','Neutral','Classic','Common','Dragon','2','3','2','Can''t be targetted by spells or Hero Powers',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Fel Reaver','c170','Minion','Neutral','Goblins Vs Gnomes','Epic','Mech','5','8','8','Whenever your opponent plays a card, discard the top 3 cards of your deck',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Fen Creeper','c171','Minion','Neutral','Classic','Common',NULL,'5','3','6','Taunt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Feugen','c172','Minion','Neutral','Naxxramas','Legendary',NULL,'5','4','7','Deathrattle: If Stalagg also died this game, summon Thaddius',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Flesheating Ghoul','c173','Minion','Neutral','Classic','Common',NULL,'3','2','3','Whenever a minion dies, gain +1 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Flying Machine','c174','Minion','Neutral','Goblins Vs Gnomes','Common','Mech','3','1','4','Windfury',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Foe Reaper 4000','c175','Minion','Neutral','Goblins Vs Gnomes','Legendary','Mech','8','6','9','Also damages the minions next to whomever he attacks',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Force-Tank MAX','c176','Minion','Neutral','Goblins Vs Gnomes','Common','Mech','8','7','7','Divine Shield',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Frost Elemental','c177','Minion','Neutral','Classic','Common',NULL,'6','5','5','Battlecry: Freeze a character',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Frostwolf Grunt','c178','Minion','Neutral','Basic','Basic',NULL,'2','2','2','Taunt','2');
INSERT INTO `SQLiteCartas` VALUES ('Frostwolf Warlord','c179','Minion','Neutral','Basic','Basic',NULL,'5','4','4','Battlecry: Gain +1/+1 for each other friendly minion on the battlefield','2');
INSERT INTO `SQLiteCartas` VALUES ('Gadgetzan Auctioneer','c180','Minion','Neutral','Classic','Rare',NULL,'6','4','4','Whenever you cast a spell, draw a card',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Gazlowe','c181','Minion','Neutral','Goblins Vs Gnomes','Legendary',NULL,'6','3','6','Whenever you cast a 1-mana spell, add a random Mech to your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Gelbin Mekkatorque','c182','Minion','Neutral','Promo','Legendary',NULL,'6','6','6','Battlecry: Summon an AWESOME invention',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Gilblin Stalker','c183','Minion','Neutral','Goblins Vs Gnomes','Common',NULL,'2','2','3','Stealth',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Gnomeregan Infantry','c184','Minion','Neutral','Goblins Vs Gnomes','Common',NULL,'3','1','5','Charge. Taunt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Gnomish Experimenter','c185','Minion','Neutral','Goblins Vs Gnomes','Rare',NULL,'3','3','2','Battlecry: Draw a card. If it''s a minion, transform it into a Chicken',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Gnomish Inventor','c186','Minion','Neutral','Basic','Basic',NULL,'4','2','4','Battlecry: Draw a card','2');
INSERT INTO `SQLiteCartas` VALUES ('Goblin Sapper','c187','Minion','Neutral','Goblins Vs Gnomes','Rare',NULL,'3','2','4','Has +4 Attack while your opponent has 6 or more cards in hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Goldshire Footman','c188','Minion','Neutral','Basic','Basic',NULL,'1','1','2','Taunt','2');
INSERT INTO `SQLiteCartas` VALUES ('Grimscale Oracle','c189','Minion','Neutral','Basic','Basic','Murloc','1','1','1','ALL other Murlocs have +1 Attack','2');
INSERT INTO `SQLiteCartas` VALUES ('Gruul','c190','Minion','Neutral','Classic','Legendary',NULL,'8','7','7','At the end of each turn, gain +1/+1',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Gurubashi Berserker','c191','Minion','Neutral','Basic','Basic',NULL,'5','2','7','Whenever this minion takes damage, gain +3 attack','2');
INSERT INTO `SQLiteCartas` VALUES ('Harrison Jones','c192','Minion','Neutral','Classic','Legendary',NULL,'5','5','4','Battlecry: Destroy your opponent''s weapon and draw cards equal to its Durability',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Harvest Golem','c193','Minion','Neutral','Classic','Common','Mech','3','2','3','Deathrattle: Summon a 2/1 Damaged Golem',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Haunted Creeper','c194','Minion','Neutral','Naxxramas','Common',NULL,'2','1','2','Deathrattle: Summon two 1/1 Spectral Spiders',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Hemet Nesignwary','c195','Minion','Neutral','Goblins Vs Gnomes','Legendary',NULL,'5','6','3','Battlecry: Destroy a Beast',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Hobgoblin','c196','Minion','Neutral','Goblins Vs Gnomes','Epic',NULL,'3','2','3','Whenever you play a 1-Attack minion, give it +2/+2',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Hogger','c197','Minion','Neutral','Classic','Legendary',NULL,'6','4','4','At the end of your turn, summon a 2/2 Gnoll with Taunt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Hungry Crab','c198','Minion','Neutral','Classic','Epic','Beast','1','1','2','Battlecry: Destroy a Murloc and gain +2/+2',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Illidan Stormrage','c199','Minion','Neutral','Classic','Legendary','Demon','6','7','5','Whenever you play a card, summon a 2/1 Flame of Azzinoth',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Illuminator','c200','Minion','Neutral','Goblins Vs Gnomes','Rare',NULL,'3','2','4','If you control a Secret at the end of your turn, restore 4 Health to your hero',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Imp Master','c201','Minion','Neutral','Classic','Common',NULL,'3','1','5','At the end of your turn, deal 1 damage to this minion and summon a 1/1 imp',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Injured Blademaster','c202','Minion','Neutral','Classic','Rare',NULL,'3','4','7','Battlecry: Deal 4 damage to HIMSELF',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ironbeak Owl','c203','Minion','Neutral','Classic','Common','Beast','2','2','1','Battlecry: Silence a minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ironforge Rifleman','c204','Minion','Neutral','Basic','Basic',NULL,'3','2','2','Battlecry: Deal 1 damage','2');
INSERT INTO `SQLiteCartas` VALUES ('Ironfur Grizzly','c205','Minion','Neutral','Basic','Basic','Beast','3','3','3','Taunt','2');
INSERT INTO `SQLiteCartas` VALUES ('Jeeves','c206','Minion','Neutral','Goblins Vs Gnomes','Rare','Mech','4','1','4','At the end of each player''s turn, that players draws until they have 3 cards',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Jungle Panther','c207','Minion','Neutral','Classic','Common',NULL,'3','4','2','Stealth',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Junkbot','c208','Minion','Neutral','Goblins Vs Gnomes','Epic','Mech','5','1','5','Whenever a friendly Mech dies, gain +2/+2',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Kel''Thuzad','c209','Minion','Neutral','Naxxramas','Legendary',NULL,'8','6','8','At the end of each turn, summon al friendly minions that died this turn',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Kezan Mystic','c210','Minion','Neutral','Goblins Vs Gnomes','Rare',NULL,'4','4','3','Battlecry: Take control of a random enemy Secret',NULL);
INSERT INTO `SQLiteCartas` VALUES ('King Mukla','c211','Minion','Neutral','Classic','Legendary','Beast','3','5','5','Battlecry: Give your opponnet 2 Bananas',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Knife Juggler','c212','Minion','Neutral','Classic','Rare',NULL,'2','3','2','After you summon a minion, deal 1 damage to a random enemy',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Kobold Geomancer','c213','Minion','Neutral','Basic','Basic',NULL,'2','2','2','Spell Damage +1','2');
INSERT INTO `SQLiteCartas` VALUES ('Leeroy Jenkins','c214','Minion','Neutral','Classic','Legendary',NULL,'5','6','2','Charge. Battlecry: Summon two 1/1 Whelps for your opponent',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Leper Gnome','c215','Minion','Neutral','Classic','Common',NULL,'1','2','1','Deathrattle: Deal 2 damage to the enemy hero',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Lightwarden','c216','Minion','Neutral','Classic','Rare',NULL,'1','1','2','Whenever a character is healed, gain +2 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Lil'' Exorcist','c217','Minion','Neutral','Goblins Vs Gnomes','Rare',NULL,'3','2','3','Taunt. Battlecry: Gain +1/+1 for each enemy Deathrattle minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Loatheb','c218','Minion','Neutral','Naxxramas','Legendary',NULL,'5','5','5','Battlecry: Enemy spells cost (5) more next turn',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Loot Hoarder','c219','Minion','Neutral','Classic','Common',NULL,'2','2','1','Deathrattle: Draw a card',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Lord of the Arena','c220','Minion','Neutral','Basic','Basic',NULL,'6','6','5','Taunt','2');
INSERT INTO `SQLiteCartas` VALUES ('Lorewalker Cho','c221','Minion','Neutral','Classic','Legendary',NULL,'2','0','4','Whenever a player cast a spell, put a copy into the other player''s hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Lost Tallstrider','c222','Minion','Neutral','Goblins Vs Gnomes','Common','Beast','4','5','4',NULL,NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mad Bomber','c223','Minion','Neutral','Classic','Common',NULL,'2','3','2','Battlecry: Deal 3 damage randomly split between all other characters',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mad Scientist','c224','Minion','Neutral','Naxxramas','Common',NULL,'2','2','2','Deathrattle: Put a Secret from your deck into the battlefield',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Madder Bomber','c225','Minion','Neutral','Goblins Vs Gnomes','Rare',NULL,'5','5','4','Battlecry: Deal 6 damage randomly split between all other characters',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Maexxna','c226','Minion','Neutral','Naxxramas','Legendary',NULL,'6','2','8','Destroy any minion damaged by this minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Magma Rager','c227','Minion','Neutral','Basic','Basic',NULL,'3','5','1',NULL,'2');
INSERT INTO `SQLiteCartas` VALUES ('Malygos','c228','Minion','Neutral','Classic','Legendary','Dragon','9','4','12','Spell Damage +5',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mana Addict','c229','Minion','Neutral','Classic','Rare',NULL,'2','1','3','Whenever you cast a spell, gain +2 Attack this turn',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mana Wraith','c230','Minion','Neutral','Classic','Rare',NULL,'2','2','2','ALL minions costs (1) more',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Master Swordsmith','c231','Minion','Neutral','Classic','Rare',NULL,'2','1','3','At the end of your turn, give another friendly minion +1 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mechanical Yeti','c232','Minion','Neutral','Goblins Vs Gnomes','Common','Mech','4','4','5','Deathrattle: Give each player a Spare Part',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mechwarper','c233','Minion','Neutral','Goblins Vs Gnomes','Common','Mech','2','2','3','Your Mechs cost (1) less',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mekgineer Thermaplugg','c234','Minion','Neutral','Goblins Vs Gnomes','Legendary','Mech','9','9','7','Whenever an enemy minion dies, summon a Leper Gnome',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Micro Machine','c235','Minion','Neutral','Goblins Vs Gnomes','Common','Mech','2','1','2','At the start of each turn, gain +1 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Millhouse Manastorm','c236','Minion','Neutral','Classic','Legendary',NULL,'2','4','4','Battlecry: Enemy spells cost (0) next turn',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mind Control Tech','c237','Minion','Neutral','Classic','Rare',NULL,'3','3','3','Battlecry: If your opponent has 4 or more minions, take control of one at random',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mini-Mage','c238','Minion','Neutral','Goblins Vs Gnomes','Epic',NULL,'4','4','1','Stealth. Spell Damage +1',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mogor the Ogre','c239','Minion','Neutral','Goblins Vs Gnomes','Legendary',NULL,'6','7','6','All minions have a 50% chance to attack the wrong enemy',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mogu''shan Warden','c240','Minion','Neutral','Classic','Common',NULL,'4','1','7','Taunt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Molten Giant','c241','Minion','Neutral','Classic','Epic',NULL,'20','8','8','Costs (1) less for each damage your hero has taken',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mountain Giant','c242','Minion','Neutral','Classic','Epic',NULL,'12','8','8','Costs (1) less for each other card in your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Murloc Raider','c243','Minion','Neutral','Basic','Basic','Murloc','1','2','1',NULL,'2');
INSERT INTO `SQLiteCartas` VALUES ('Murloc Tidecaller','c244','Minion','Neutral','Classic','Rare','Murloc','1','1','2','Whenever a Murloc is summoned, gain +1 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Murloc Tidehunter','c245','Minion','Neutral','Basic','Basic','Murloc','2','2','1','Battlecry: Summon a 1/1 Murloc Scout','2');
INSERT INTO `SQLiteCartas` VALUES ('Murloc Warleader','c246','Minion','Neutral','Classic','Epic','Murloc','3','3','3','ALL other Murlocs have +2/+1',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Nat Pagle','c247','Minion','Neutral','Classic','Legendary',NULL,'2','0','4','At the start of your turn, you have a 50% chance to draw an extra card',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Nerub''ar Weblord','c248','Minion','Neutral','Naxxramas','Common',NULL,'2','1','4','Minions with Battlecry cost (2) more',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Nerubian Egg','c249','Minion','Neutral','Naxxramas','Rare',NULL,'2','0','2','Deathrattle: Summon a 4/4 nerubian',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Nightblade','c250','Minion','Neutral','Basic','Basic',NULL,'5','4','4','Battlecry: Deal 3 damage to the enemy hero','2');
INSERT INTO `SQLiteCartas` VALUES ('Novice Engineer','c251','Minion','Neutral','Basic','Basic',NULL,'2','1','1','Battlecry: Draw a card','2');
INSERT INTO `SQLiteCartas` VALUES ('Nozdormu','c252','Minion','Neutral','Classic','Legendary','Dragon','9','8','8','Players only have 15 seconds to take their turns',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Oasis Snapjaw','c253','Minion','Neutral','Basic','Basic','Beast','4','2','7',NULL,'2');
INSERT INTO `SQLiteCartas` VALUES ('Ogre Brute','c254','Minion','Neutral','Goblins Vs Gnomes','Common',NULL,'3','4','4','50% chance to attack the wrong enemy',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ogre Magi','c255','Minion','Neutral','Basic','Basic',NULL,'4','4','4','Spell Damage +1','2');
INSERT INTO `SQLiteCartas` VALUES ('Old Murk-Eye','c256','Minion','Neutral','Promo','Legendary','Murloc','4','2','4','Charge. Has +1 Attack for each other Murloc on the battlefield',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Onyxia','c257','Minion','Neutral','Classic','Legendary','Dragon','9','8','8','Battlecry: Summon 1/1 Whelps until your side of the battlefield is full',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Piloted Shredder','c258','Minion','Neutral','Goblins Vs Gnomes','Common','Mech','4','4','3','Deathrattle: Summon a random 2-Cost minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Piloted Sky Golem','c259','Minion','Neutral','Goblins Vs Gnomes','Epic','Mech','6','6','4','Deathrattle: Summon a random 4-Cost minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Pint-Sized Summoner','c260','Minion','Neutral','Classic','Rare',NULL,'2','2','2','The first minion you play each turn costs (1) less',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Priestess of Elune','c261','Minion','Neutral','Classic','Common',NULL,'6','5','4','Battlecry: Restore 4 Health to your hero',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Puddlestomper','c262','Minion','Neutral','Goblins Vs Gnomes','Common','Murloc','2','3','2',NULL,NULL);
INSERT INTO `SQLiteCartas` VALUES ('Questing Adventurer','c263','Minion','Neutral','Classic','Rare',NULL,'3','2','2','Whenever you play a card, gain +1/+1',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Raging Worgen','c264','Minion','Neutral','Classic','Common',NULL,'3','3','3','Enrage: Windfury and +1 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ragnaros the Firelord','c265','Minion','Neutral','Classic','Legendary',NULL,'8','8','8','Can''t Attack. At the end of your turn, deal 8 damage to a random enemy',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Raid Leader','c266','Minion','Neutral','Basic','Basic',NULL,'3','2','2','Your other minions have +1 Attack','2');
INSERT INTO `SQLiteCartas` VALUES ('Ravenholdt Assassin','c267','Minion','Neutral','Classic','Rare',NULL,'7','7','5','Stealth',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Razorfen Hunter','c268','Minion','Neutral','Basic','Basic',NULL,'3','2','3','Battlecry: Summon a 1/1 Boar','2');
INSERT INTO `SQLiteCartas` VALUES ('Reckless Rocketeer','c269','Minion','Neutral','Basic','Basic',NULL,'6','5','2','Charge','2');
INSERT INTO `SQLiteCartas` VALUES ('Recombobulator','c270','Minion','Neutral','Goblins Vs Gnomes','Epic',NULL,'2','3','2','Battlecry: Transform a friendly minion into a random minion with the same Cost',NULL);
INSERT INTO `SQLiteCartas` VALUES ('River Crocolisk','c271','Minion','Neutral','Basic','Basic','Beast','2','2','3',NULL,'2');
INSERT INTO `SQLiteCartas` VALUES ('Salty Dog','c272','Minion','Neutral','Goblins Vs Gnomes','Common','Pirate','5','7','4',NULL,NULL);
INSERT INTO `SQLiteCartas` VALUES ('Scarlet Crusader','c273','Minion','Neutral','Classic','Common',NULL,'3','3','1','Divine Shield',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Sea Giant','c274','Minion','Neutral','Classic','Epic',NULL,'10','8','8','Costs (1) less for each other minion on the battlefield',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Secretkeeper','c275','Minion','Neutral','Classic','Rare',NULL,'1','1','2','Whenever a secret is played, gain +1/+1',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Sen''jin Shieldmasta','c276','Minion','Neutral','Basic','Basic',NULL,'4','3','5','Taunt','2');
INSERT INTO `SQLiteCartas` VALUES ('Shade of Naxxramas','c277','Minion','Neutral','Naxxramas','Epic',NULL,'3','2','2','Stealth. At the start of your turn, gain +1/+1',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Shattered Sun Cleric','c278','Minion','Neutral','Basic','Basic',NULL,'3','3','2','Battlecry: Give a friendly minion +1/+1','2');
INSERT INTO `SQLiteCartas` VALUES ('Shieldbearer','c279','Minion','Neutral','Classic','Common',NULL,'1','0','4','Taunt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ship''s Cannon','c280','Minion','Neutral','Goblins Vs Gnomes','Common',NULL,'2','2','3','Whenever you summon a Pirate, deal 2 damage to a random enemy',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Silver Hand Knight','c281','Minion','Neutral','Classic','Common',NULL,'5','4','4','Battlecry: Summon a 2/2 Squire',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Silverback Patriarch','c282','Minion','Neutral','Basic','Basic','Beast','3','1','4','Taunt','2');
INSERT INTO `SQLiteCartas` VALUES ('Silvermoon Guardian','c283','Minion','Neutral','Classic','Common',NULL,'4','3','3','Divine Shield',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Sludge Belcher','c284','Minion','Neutral','Naxxramas','Rare',NULL,'5','3','5','Taunt. Deathrattle: Summon a 1/2 Slime with Taunt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Sneed''s Old Shredder','c285','Minion','Neutral','Goblins Vs Gnomes','Legendary','Mech','8','5','7','Deathrattle: Summon a random legendary minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Southsea Captain','c286','Minion','Neutral','Classic','Epic','Pirate','3','3','3','Your other Pirates have +1/+1',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Southsea Deckhand','c287','Minion','Neutral','Classic','Common','Pirate','1','2','1','Has Charge while you have a weapon equipped',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Spectral Knight','c288','Minion','Neutral','Naxxramas','Common',NULL,'5','4','6','Can''t be targeted by spells or Hero Powers',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Spellbreaker','c289','Minion','Neutral','Classic','Common',NULL,'4','4','3','Battlecry: Silence a minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Spider Tank','c290','Minion','Neutral','Goblins Vs Gnomes','Common','Mech','3','3','4',NULL,NULL);
INSERT INTO `SQLiteCartas` VALUES ('Spiteful Smith','c291','Minion','Neutral','Classic','Common',NULL,'5','4','6','Enrage: Your weapon has +2 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Stalagg','c292','Minion','Neutral','Naxxramas','Legendary',NULL,'5','7','4','Deathrattle: If Feugen also died this game, summon Thaddius',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Stampeding Kodo','c293','Minion','Neutral','Classic','Rare','Beast','5','3','5','Battlecry: Destroy a random enemy minion with 2 or less Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Stoneskin Gargoyle','c294','Minion','Neutral','Naxxramas','Common',NULL,'3','1','4','At the start of your turn, restore this minion to full Health',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Stonesplinter Trogg','c295','Minion','Neutral','Goblins Vs Gnomes','Common',NULL,'2','2','3','Whenever your opponent casts a spell, gain +1 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Stonetusk Boar','c296','Minion','Neutral','Basic','Basic','Beast','1','1','1','Charge','2');
INSERT INTO `SQLiteCartas` VALUES ('Stormpike Commando','c297','Minion','Neutral','Basic','Basic',NULL,'5','4','2','Battlecry: Deal 2 damage','2');
INSERT INTO `SQLiteCartas` VALUES ('Stormwind Champion','c298','Minion','Neutral','Basic','Basic',NULL,'7','6','6','Your other minions have +1/+1','2');
INSERT INTO `SQLiteCartas` VALUES ('Stormwind Knight','c299','Minion','Neutral','Basic','Basic',NULL,'4','2','5','Charge','2');
INSERT INTO `SQLiteCartas` VALUES ('Stranglethorn Tiger','c300','Minion','Neutral','Classic','Common','Beast','5','5','5','Stealth',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Sunfury Protector','c301','Minion','Neutral','Classic','Rare',NULL,'2','2','3','Battlecry: Give adjacent minions Taunt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Sunwalker','c302','Minion','Neutral','Classic','Rare',NULL,'6','4','5','Taunt. Divine Shield',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Sylvanas Windrunner','c303','Minion','Neutral','Classic','Legendary',NULL,'6','5','5','Deathrattle: Take control of a random enemy minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Target Dummy','c304','Minion','Neutral','Goblins Vs Gnomes','Rare','Mech','0','0','2','Taunt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Tauren Warrior','c305','Minion','Neutral','Classic','Common',NULL,'3','2','3','Taunt. Enrage: +3 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('The Beast','c306','Minion','Neutral','Classic','Legendary','Beast','6','9','7','Deathrattle: Summon a 3/3 Finkle Einhorn for your opponent',NULL);
INSERT INTO `SQLiteCartas` VALUES ('The Black Knight','c307','Minion','Neutral','Classic','Legendary',NULL,'6','4','5','Battlecry: Destroy an enemy minion with Taunt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Thrallmar Farseer','c308','Minion','Neutral','Classic','Common',NULL,'3','2','3','Windfury',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Tinkertown Technician','c309','Minion','Neutral','Goblins Vs Gnomes','Common',NULL,'3','3','3','Battlecry: If you have a Mech, gain +1/+1 and add a Spare Part to your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Tinkmaster Overspark','c310','Minion','Neutral','Classic','Legendary',NULL,'3','3','3','Battlecry: Transform another random minion into a 5/5 Devilsaur or a 1/1 Squirrel',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Toshley','c311','Minion','Neutral','Goblins Vs Gnomes','Legendary',NULL,'6','5','7','Battlecry and Deathrattle: Add a Spare Part cart to your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Troggzor the Earthinator','c312','Minion','Neutral','Goblins Vs Gnomes','Legendary',NULL,'7','6','6','Whenever your opponent cast a spell, summon a Burly Rockjaw Trogg',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Twilight Drake','c313','Minion','Neutral','Classic','Rare','Dragon','4','4','1','Battlecry: Gain +1 Health for each other card in your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Undertaker','c314','Minion','Neutral','Naxxramas','Common',NULL,'1','1','2','Whenever you summon a minion with Deathrattle, gain +1/+1',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Unstable Ghoul','c315','Minion','Neutral','Naxxramas','Common',NULL,'2','1','3','Taunt. Deathrattle: Deal 1 damage to all minions',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Venture Co. Mercenary','c316','Minion','Neutral','Classic','Common',NULL,'5','7','6','Your minions costs (3) more',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Violet Teacher','c317','Minion','Neutral','Classic','Rare',NULL,'4','3','5','Whenever you cast a spell, summon a 1/1 Violet Apprentice',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Voodoo Doctor','c318','Minion','Neutral','Basic','Basic',NULL,'1','2','1','Battlecry: Restore 2 Health','2');
INSERT INTO `SQLiteCartas` VALUES ('Wailing Soul','c319','Minion','Neutral','Naxxramas','Rare',NULL,'4','3','5','Battlecry: Silence your other minions',NULL);
INSERT INTO `SQLiteCartas` VALUES ('War Golem','c320','Minion','Neutral','Basic','Basic',NULL,'7','7','7',NULL,'2');
INSERT INTO `SQLiteCartas` VALUES ('Wild Pyromancer','c321','Minion','Neutral','Classic','Rare',NULL,'2','3','2','After you cast a spell, deal 1 damage to ALL minions',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Windfury Harpy','c322','Minion','Neutral','Classic','Common',NULL,'6','4','5','Windfury',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Wisp','c323','Minion','Neutral','Classic','Common',NULL,'0','1','1',NULL,NULL);
INSERT INTO `SQLiteCartas` VALUES ('Wolfrider','c324','Minion','Neutral','Basic','Basic',NULL,'3','3','1','Charge','2');
INSERT INTO `SQLiteCartas` VALUES ('Worgen Infiltrator','c325','Minion','Neutral','Classic','Common',NULL,'1','2','1','Stealth',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Young Dragonhawk','c326','Minion','Neutral','Classic','Common','Beast','1','1','1','Windfury',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Young Priestess','c327','Minion','Neutral','Classic','Rare',NULL,'1','2','1','At the end of your turn, give another random friendly minion +1 Health',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Youthful Brewmaster','c328','Minion','Neutral','Classic','Common',NULL,'2','3','2','Battlecry: Return a friendly minion from the battlefield to your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ysera','c329','Minion','Neutral','Classic','Legendary','Dragon','9','4','12','At the end of your turn, draw a Dream Card',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Zombie Chow','c330','Minion','Neutral','Naxxramas','Common',NULL,'1','2','3','Deathrattle: Restore 5 Health to the enemy hero',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Aldor Peacekeeper','c331','Minion','Paladin','Classic','Rare',NULL,'3','3','3','Battlecry: Change an enemy minion''s Attack to 1',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Argent Protector','c332','Minion','Paladin','Classic','Common',NULL,'2','2','2','Battlecry: Give a friendly minion Divine Shield',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Avenge','c333','Spell','Paladin','Naxxramas','Common',NULL,'1',NULL,NULL,'Secret: When one of your minions dies, give a random friendly minion +3/+2',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Avenging Wrath','c334','Spell','Paladin','Classic','Epic',NULL,'6',NULL,NULL,'Deal 8 damage randomly split among enemy characters',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Blessed Champion','c335','Spell','Paladin','Classic','Rare',NULL,'5',NULL,NULL,'Double a minion''s Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Blessing of Kings','c336','Spell','Paladin','Basic','Basic',NULL,'4',NULL,NULL,'Give a minion +4/+4 (+4 Attack/+4 Health)','2');
INSERT INTO `SQLiteCartas` VALUES ('Blessing of Might','c337','Spell','Paladin','Basic','Basic',NULL,'1',NULL,NULL,'Give a minion +3 Attack','2');
INSERT INTO `SQLiteCartas` VALUES ('Blessing of Widsom','c338','Spell','Paladin','Classic','Common',NULL,'1',NULL,NULL,'Choose a minion. Whenever it attacks, draw a card',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Bolvar Fordragon','c339','Minion','Paladin','Goblins Vs Gnomes','Legendary',NULL,'5','1','7','Whenever a friendly minion dies while this is in your hand, gain +1 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Cobalt Guardian','c340','Minion','Paladin','Goblins Vs Gnomes','Rare','Mech','5','6','3','Whenever you summon a Mech, gain Divine Shield',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Coghammer','c341','Weapon','Paladin','Goblins Vs Gnomes','Epic',NULL,'3','2','3','Battlecry: Give a random friendly minion Divine Shield and Taunt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Consecration','c342','Spell','Paladin','Basic','Basic',NULL,'4',NULL,NULL,'Deal 2 damage to all enemies','2');
INSERT INTO `SQLiteCartas` VALUES ('Divine Favor','c343','Spell','Paladin','Classic','Rare',NULL,'3',NULL,NULL,'Draw cards until you have as many in your hand as your opponent',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Equality','c344','Spell','Paladin','Classic','Rare',NULL,'2',NULL,NULL,'Change the Health of ALL minions to 1',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Eye for an Eye','c345','Spell','Paladin','Classic','Common',NULL,'1',NULL,NULL,'Secret: When your hero takes damage, deal that much damage to the enemy hero',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Guardian of Kings','c346','Minion','Paladin','Basic','Basic',NULL,'7',NULL,NULL,'Battlecry: Restore 6 Health to your hero','2');
INSERT INTO `SQLiteCartas` VALUES ('Hammer of Wrath','c347','Spell','Paladin','Basic','Basic',NULL,'4',NULL,NULL,'Deal 3 damage. Draw a card','2');
INSERT INTO `SQLiteCartas` VALUES ('Hand of Protection','c348','Spell','Paladin','Basic','Basic',NULL,'1',NULL,NULL,'Give a minion Divine Shield','2');
INSERT INTO `SQLiteCartas` VALUES ('Holy Light','c349','Spell','Paladin','Basic','Basic',NULL,'2',NULL,NULL,'Restore 6 health','2');
INSERT INTO `SQLiteCartas` VALUES ('Holy Wrath','c350','Spell','Paladin','Classic','Rare',NULL,'5',NULL,NULL,'Draw a card and deal damage equal to its cost',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Humility','c351','Spell','Paladin','Basic','Basic',NULL,'1',NULL,NULL,'Change a minion''s Attack to 1','2');
INSERT INTO `SQLiteCartas` VALUES ('Lay on Hands','c352','Spell','Paladin','Classic','Epic',NULL,'8',NULL,NULL,'Restore 8 Health. Draw 3 cards',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Light''s Justice','c353','Weapon','Paladin','Basic','Basic',NULL,'1','1','4',NULL,'2');
INSERT INTO `SQLiteCartas` VALUES ('Muster for Battle','c354','Spell','Paladin','Goblins Vs Gnomes','Rare',NULL,'3',NULL,NULL,'Summon three 1/1 Silver Hand Recruits. Equip a 1/4 weapon',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Noble Sacrifice','c355','Spell','Paladin','Classic','Common',NULL,'1',NULL,NULL,'Secret: When an enemy attacks, summon a 2/1 Defender as the new target',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Quartermaster','c356','Minion','Paladin','Goblins Vs Gnomes','Epic',NULL,'5','2','5','Battlecry: Give your Silver Hand Recruits +2/+2',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Redemption','c357','Spell','Paladin','Classic','Common',NULL,'1',NULL,NULL,'Secret: When one of your minions dies, return it to life with 1 Health',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Repentance','c358','Spell','Paladin','Classic','Common',NULL,'1',NULL,NULL,'Secret: When your opponent plays a minion, reduce its Health to 1',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Scarlet Purifier','c359','Minion','Paladin','Goblins Vs Gnomes','Rare',NULL,'3','4','3','Battlecry: Deal 2 damage to all minions with Deathrattle',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Seal of Light','c360','Spell','Paladin','Goblins Vs Gnomes','Common',NULL,'2',NULL,NULL,'Restore 4 Health to your hero and gain +2 Attack this turn',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Shielded Minibot','c361','Minion','Paladin','Goblins Vs Gnomes','Common','Mech','2','2','2','Divine Shield',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Sword of Justice','c362','Weapon','Paladin','Classic','Epic',NULL,'3','1','5','Whenever you summon a minion, give it +1/+1 and this loses 1 Durability',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Tirion Fordring','c363','Minion','Paladin','Classic','Legendary',NULL,'8','6','6','Divine Shield. Taunt. Deathrattle: Equip a 5/3 Ashbringer',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Truesilver Champion','c364','Weapon','Paladin','Basic','Basic',NULL,'4','4','2','Whenever your hero attacks, restore 2 Health to it','2');
INSERT INTO `SQLiteCartas` VALUES ('Auchenai Soulpriest','c365','Minion','Priest','Classic','Rare',NULL,'4','3','5','Your cards and powers that restore Health now deal damage instead',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Cabal Shadow Priest','c366','Minion','Priest','Classic','Epic',NULL,'6','4','5','Battlecry: Take control of an enemy minion that has 2 or less Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Circle of Healing','c367','Spell','Priest','Classic','Common',NULL,'0',NULL,NULL,'Restore 4 Health to ALL characters',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Dark Cultist','c368','Minion','Priest','Naxxramas','Common',NULL,'3','3','4','Deathrattle: Give a friendly minion +3 Health',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Divine Spirit','c369','Spell','Priest','Basic','Basic',NULL,'2',NULL,NULL,'Double a minion''s Health','2');
INSERT INTO `SQLiteCartas` VALUES ('Holy Fire','c370','Spell','Priest','Classic','Rare',NULL,'6',NULL,NULL,'Deal 5 damage. Restore 5 Health to your hero',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Holy Nova','c371','Spell','Priest','Basic','Basic',NULL,'5',NULL,NULL,'Deal 2 damage to all enemies. Restore 2 Health to all friendly characters','2');
INSERT INTO `SQLiteCartas` VALUES ('Holy Smite','c372','Spell','Priest','Basic','Basic',NULL,'1',NULL,NULL,'Deal 2 damage','2');
INSERT INTO `SQLiteCartas` VALUES ('Inner Fire','c373','Spell','Priest','Classic','Common',NULL,'1',NULL,NULL,'Change a minion''s Attack to be equal to its Health',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Light of the Naaru','c374','Spell','Priest','Goblins Vs Gnomes','Rare',NULL,'1',NULL,NULL,'Restore 3 Health. If the target is still damaged, summon a Lightwarden',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Lightbomb','c375','Spell','Priest','Goblins Vs Gnomes','Epic',NULL,'6',NULL,NULL,'Deal damage to each minion equal to its Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Lightspawn','c376','Minion','Priest','Classic','Common',NULL,'4','0','5','This minion''s Attack is always equal to its Health',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Lightwell','c377','Minion','Priest','Classic','Rare',NULL,'2','0','5','At the start of your turn, restore 3 Health to a damaged friendly character',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mass Dispel','c378','Spell','Priest','Classic','Rare',NULL,'4',NULL,NULL,'Silence all enemy minions. Draw a card',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mind Blast','c379','Spell','Priest','Basic','Basic',NULL,'2',NULL,NULL,'Deal 5 damage to the enemy hero','2');
INSERT INTO `SQLiteCartas` VALUES ('Mind Control','c380','Spell','Priest','Basic','Basic',NULL,'10',NULL,NULL,'Take control of an enemy minion','2');
INSERT INTO `SQLiteCartas` VALUES ('Mind Vision','c381','Spell','Priest','Basic','Basic',NULL,'1',NULL,NULL,'Put a copy of a random card in your opponent''s hand into your hand','2');
INSERT INTO `SQLiteCartas` VALUES ('Mindgames','c382','Spell','Priest','Classic','Epic',NULL,'4',NULL,NULL,'Put a copy of a random minion from your opponent''s deck into the battlefield',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Northshire Cleric','c383','Minion','Priest','Basic','Basic',NULL,'1','1','3','Whenever a minion is healed, draw a card','2');
INSERT INTO `SQLiteCartas` VALUES ('Power Word - Shield','c384','Spell','Priest','Basic','Basic',NULL,'1',NULL,NULL,'Give a minion +2 health. Draw a card','2');
INSERT INTO `SQLiteCartas` VALUES ('Prophet Velen','c385','Minion','Priest','Classic','Legendary',NULL,'7',NULL,NULL,'Double the damage and healing of your spells and hero powers',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Shadow Madness','c386','Spell','Priest','Classic','Rare',NULL,'4',NULL,NULL,'Gain control of an enemy minion with 3 or less Attack until end of turn',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Shadow Word - Death','c387','Spell','Priest','Basic','Basic',NULL,'3',NULL,NULL,'Destroy a minion with an Attack of 3 or more','2');
INSERT INTO `SQLiteCartas` VALUES ('Shadow Word - Pain','c388','Spell','Priest','Basic','Basic',NULL,'2',NULL,NULL,'Destroy a minion with 3 or less Attack','2');
INSERT INTO `SQLiteCartas` VALUES ('Shadowbomber','c389','Minion','Priest','Goblins Vs Gnomes','Epic',NULL,'1','2','1','Battlecry: Deal 3 damage to each hero',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Shadowboxer','c390','Minion','Priest','Goblins Vs Gnomes','Rare','Mech','2','2','3','Whenever a character is healed, deal 1 damage to a random enemy',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Shadowform','c391','Spell','Priest','Classic','Epic',NULL,'3',NULL,NULL,'Your Hero Power becomes ''Deal 2 damage''. If already in Shadowform: 3 damage',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Shrinkmeister','c392','Minion','Priest','Goblins Vs Gnomes','Common',NULL,'2','3','2','Battlecry: Give a minion -2 Attack this turn',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Silence','c393','Spell','Priest','Classic','Common',NULL,'0',NULL,NULL,'Silence a minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Temple Enforcer','c394','Minion','Priest','Classic','Common',NULL,'6','6','6','Battlecry: Give a friendly minion +3 Health',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Thoughtsteal','c395','Spell','Priest','Classic','Common',NULL,'3',NULL,NULL,'Copy 2 cards from your opponent''s deck and put them into your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Upgraded Repair Bot','c396','Minion','Priest','Goblins Vs Gnomes','Rare','Mech','5','5','5','Battlecry: Give a friendly Mech +4 Health',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Velen''s Chosen','c397','Spell','Priest','Goblins Vs Gnomes','Common',NULL,'3',NULL,NULL,'Give a minion +2/+4 and Spell Damage +1',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Vol''jin','c398','Minion','Priest','Goblins Vs Gnomes','Legendary',NULL,'5','6','2','Battlecry: Swap Health with another minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Anub''ar Ambusher','c399','Minion','Rogue','Naxxramas','Common',NULL,'4','5','5','Deathrattle: Return a random friendly minion to your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Assassin''s Blade','c400','Weapon','Rogue','Basic','Basic',NULL,'5','3','4',NULL,'2');
INSERT INTO `SQLiteCartas` VALUES ('Assassinate','c401','Spell','Rogue','Basic','Basic',NULL,'5',NULL,NULL,'Destroy an enemy minion','2');
INSERT INTO `SQLiteCartas` VALUES ('Backstab','c402','Spell','Rogue','Basic','Basic',NULL,'0',NULL,NULL,'Deal 2 damage to an undamaged minion','2');
INSERT INTO `SQLiteCartas` VALUES ('Betrayal','c403','Spell','Rogue','Classic','Common',NULL,'2',NULL,NULL,'Force an enemy minion to deal its damage to the minions next to it',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Blade Flurry','c404','Spell','Rogue','Classic','Rare',NULL,'2',NULL,NULL,'Destroy your weapon and deal its damage to all enemies',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Cogmaster''s Wrench','c405','Weapon','Rogue','Goblins Vs Gnomes','Epic',NULL,'3','1','3','Has +2 Attack while you have a Mech',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Cold Blood','c406','Spell','Rogue','Classic','Common',NULL,'1',NULL,NULL,'Give a minion +2 Attack. Combo: +4 Attack instead',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Conceal','c407','Spell','Rogue','Classic','Common',NULL,'1',NULL,NULL,'Give your minions Stealth until your next turn',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Deadly Poison','c408','Spell','Rogue','Basic','Basic',NULL,'1',NULL,NULL,'Give your weapon +2 Attack','2');
INSERT INTO `SQLiteCartas` VALUES ('Defias Ringleader','c409','Minion','Rogue','Classic','Common',NULL,'2','2','2','Combo: Summon a 2/1 Defias Bandit',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Edwin VanCleef','c410','Minion','Rogue','Classic','Legendary',NULL,'3','2','2','Combo: Gain +2/+2 for each card played earlier this turn',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Eviscerate','c411','Spell','Rogue','Classic','Common',NULL,'2',NULL,NULL,'Deal 2 damage. Combo: Deal 4 damage instead',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Fan of Knives','c412','Spell','Rogue','Basic','Basic',NULL,'3',NULL,NULL,'Deal 1 damage to all enemy minions. Draw a card','2');
INSERT INTO `SQLiteCartas` VALUES ('Goblin Auto-Barber','c413','Minion','Rogue','Goblins Vs Gnomes','Common','Mech','2','3','2','Battlecry: Give your weapon +1 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Headcrack','c414','Spell','Rogue','Classic','Rare',NULL,'2',NULL,NULL,'Deal 2 damage to the enemy hero. Combo: Return this to your hand next turn',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Iron Sensei','c415','Minion','Rogue','Goblins Vs Gnomes','Rare','Mech','3','2','2','At the end of your turn, give another friendly Mech +2/+2',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Kidnapper','c416','Minion','Rogue','Classic','Epic',NULL,'6','5','3','Combo: Return a minion to its owner''s hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Master of Disguise','c417','Minion','Rogue','Classic','Rare',NULL,'4','4','4','Battlecry: Give a friendly minion Stealth',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ogre Ninja','c418','Minion','Rogue','Goblins Vs Gnomes','Rare',NULL,'5','6','6','Stealth. 50% chance to attack the wrong enemy',NULL);
INSERT INTO `SQLiteCartas` VALUES ('One-eyed Cheat','c419','Minion','Rogue','Goblins Vs Gnomes','Rare','Pirate','2','4','1','Whenever you summon a Pirate, gain Stealth',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Patient Assassin','c420','Minion','Rogue','Classic','Epic',NULL,'2','1','1','Stealth. Destroy any minion damaged by this minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Perdition''s Blade','c421','Weapon','Rogue','Classic','Rare',NULL,'3','2','2','Battlecry: Deal 1 damage. Combo: Deal 2 damage instead',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Preparation','c422','Spell','Rogue','Classic','Epic',NULL,'0',NULL,NULL,'The next spell you cast this turn costs (3) less',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Sabotage','c423','Spell','Rogue','Goblins Vs Gnomes','Epic',NULL,'4',NULL,NULL,'Destroy a random enemy minion. Combo: And your opponent''s weapon',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Sap','c424','Spell','Rogue','Basic','Basic',NULL,'2',NULL,NULL,'Return an enemy minion to your opponent''s hand','2');
INSERT INTO `SQLiteCartas` VALUES ('Shadowstep','c425','Spell','Rogue','Classic','Common',NULL,'0',NULL,NULL,'Return a friendly minion to your hand. It costs (2) less',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Shiv','c426','Spell','Rogue','Basic','Basic',NULL,'2',NULL,NULL,'Deal 1 damage. Draw a card','2');
INSERT INTO `SQLiteCartas` VALUES ('SI-7 Agent','c427','Minion','Rogue','Classic','Rare',NULL,'3','3','3','Combo: Deal 2 damage',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Sinister Strike','c428','Spell','Rogue','Basic','Basic',NULL,'1',NULL,NULL,'Deal 3 damage to the enemy hero','2');
INSERT INTO `SQLiteCartas` VALUES ('Sprint','c429','Spell','Rogue','Basic','Basic',NULL,'7',NULL,NULL,'Draw 4 cards','2');
INSERT INTO `SQLiteCartas` VALUES ('Tinker''s Sharpsword Oil','c430','Spell','Rogue','Goblins Vs Gnomes','Common',NULL,'4',NULL,NULL,'Give your weapon +3 Attack. Combo: Give a random friendly minion +3 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Trade Prince Gallywix','c431','Minion','Rogue','Goblins Vs Gnomes','Legendary',NULL,'6','5','8','Whenever your opponent casts a spell, gain a copy of it and give them a Coin',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Vanish','c432','Spell','Rogue','Basic','Basic',NULL,'6',NULL,NULL,'Return all minion''s to their owner''s hand','2');
INSERT INTO `SQLiteCartas` VALUES ('Al''Akir the Windlord','c433','Minion','Shaman','Classic','Legendary',NULL,'8','3','5','Windfury, Charge, Divine Shield, Taunt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ancestor''s Call','c434','Spell','Shaman','Goblins Vs Gnomes','Epic',NULL,'4',NULL,NULL,'Put a random minion from each player''s hand into the battlefield',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ancestral Healing','c435','Spell','Shaman','Basic','Basic',NULL,'0',NULL,NULL,'Restore a minion to full Health and give it Taunt','2');
INSERT INTO `SQLiteCartas` VALUES ('Ancestral Spirit','c436','Spell','Shaman','Classic','Rare',NULL,'2',NULL,NULL,'Give a minion Deathrattle: Resummon this minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Bloodlust','c437','Spell','Shaman','Basic','Basic',NULL,'5',NULL,NULL,'Give your minions +3 Attack this turn','2');
INSERT INTO `SQLiteCartas` VALUES ('Crackle','c438','Spell','Shaman','Goblins Vs Gnomes','Common',NULL,'2',NULL,NULL,'Deal 3-6 damage. Overload (1)',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Doomhammer','c439','Weapon','Shaman','Classic','Epic',NULL,'5','2','8','Windfury. Overload: (2)',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Dunemaul Shaman','c440','Minion','Shaman','Goblins Vs Gnomes','Rare',NULL,'4','5','4','Windfury, Overload: (1) 50% chance to attack the wrong enemy',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Dust Devil','c441','Minion','Shaman','Classic','Common',NULL,'1','3','1','Windfury. Overload: (2)',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Earth Elemental','c442','Minion','Shaman','Classic','Epic',NULL,'5','7','8','Taunt. Overload: (3)',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Earth Shock','c443','Spell','Shaman','Classic','Common',NULL,'1',NULL,NULL,'Silence a minion, then deal 1 damage to it',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Far Sight','c444','Spell','Shaman','Classic','Epic',NULL,'3',NULL,NULL,'Draw a card. That card costs (3) less',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Feral Spirit','c445','Spell','Shaman','Classic','Rare',NULL,'3',NULL,NULL,'Summon two 2/3 Spirit Wolves with Taunt. Overload: (2)',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Fire Elemental','c446','Minion','Shaman','Basic','Basic',NULL,'6','6','5','Battlecry: Deal 3 damage','2');
INSERT INTO `SQLiteCartas` VALUES ('Flametongue Totem','c447','Minion','Shaman','Basic','Basic','Totem','2','0','3','Adjacent minions have +2 Attack','2');
INSERT INTO `SQLiteCartas` VALUES ('Forked Lightning','c448','Spell','Shaman','Classic','Common',NULL,'1',NULL,NULL,'Deal 2 damage to 2 random enemy minions. Overload: (2)',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Frost Shock','c449','Spell','Shaman','Basic','Basic',NULL,'1',NULL,NULL,'Deal 1 damage to an enemy character and Freeze it','2');
INSERT INTO `SQLiteCartas` VALUES ('Hex','c450','Spell','Shaman','Basic','Basic',NULL,'3',NULL,NULL,'Transform a minion into a 0/1 Frog with Taunt','2');
INSERT INTO `SQLiteCartas` VALUES ('Lava Burst','c451','Spell','Shaman','Classic','Rare',NULL,'3',NULL,NULL,'Deal 5 damage. Overload: (2)',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Lightning Bolt','c452','Spell','Shaman','Classic','Common',NULL,'1',NULL,NULL,'Deal 3 damage. Overload: (1)',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Lightning Storm','c453','Spell','Shaman','Classic','Rare',NULL,'3',NULL,NULL,'Deal 2-3 damage to all enemy minions. Overload: (2)',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mana Tide Totem','c454','Minion','Shaman','Classic','Rare',NULL,'3','0','3','At the end of your turn, draw a card',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Neptulon','c455','Minion','Shaman','Goblins Vs Gnomes','Legendary',NULL,'7','7','7','Battlecry: Add 4 random Murlocs to your hand. Overload: (3)',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Powermace','c456','Weapon','Shaman','Goblins Vs Gnomes','Rare',NULL,'3','3','2','Deathrattle: Give a random friendly Mech +2/+2',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Reincarnate','c457','Spell','Shaman','Naxxramas','Common',NULL,'2',NULL,NULL,'Destroy a minion, then return it to life with full Health',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Rockbiter Weapon','c458','Spell','Shaman','Basic','Basic',NULL,'1',NULL,NULL,'Give a friendly character +3 Attack this turn','2');
INSERT INTO `SQLiteCartas` VALUES ('Siltfin Spiritwalker','c459','Minion','Shaman','Goblins Vs Gnomes','Epic','Murloc','4','2','5','Whenever another friendly Murloc dies, draw a card. Overload (1)',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Stormforged Axe','c460','Weapon','Shaman','Classic','Common',NULL,'2','2','3','Overload: (1)',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Totemic Might','c461','Spell','Shaman','Basic','Basic',NULL,'0',NULL,NULL,'Give your Totems +2 Health','2');
INSERT INTO `SQLiteCartas` VALUES ('Unbound Elemental','c462','Minion','Shaman','Classic','Common',NULL,'3','2','4','Whenever you play a card with Overload, gain +1/+1',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Vitality Totem','c463','Minion','Shaman','Goblins Vs Gnomes','Rare','Totem','2','0','3','At the end of your turn, restore 4 Health to your hero',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Whirling Zap-o-matic','c464','Minion','Shaman','Goblins Vs Gnomes','Common','Mech','2','3','2','Windfury',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Windfury','c465','Spell','Shaman','Basic','Basic',NULL,'2',NULL,NULL,'Give a minion Windfury','2');
INSERT INTO `SQLiteCartas` VALUES ('Windspeaker','c466','Minion','Shaman','Basic','Basic',NULL,'4','3','3','Battlecry: Give a friendly minion Windfury','2');
INSERT INTO `SQLiteCartas` VALUES ('Anima Golem','c467','Minion','Warlock','Goblins Vs Gnomes','Epic','Mech','6','9','9','At the end of each turn, destroy this minion if it''s your only one',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Bane of Doom','c468','Spell','Warlock','Classic','Epic',NULL,'5',NULL,NULL,'Deal 2 damage to a character. If that kills it, summon a random Demon',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Blood Imp','c469','Minion','Warlock','Classic','Common','Demon','1','0','1','Stealth. At the end of your turn, give another random friendly minion +1 Health',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Corruption','c470','Spell','Warlock','Basic','Basic',NULL,'1',NULL,NULL,'Choose an enemy minion. At the start of your turn, destroy it','2');
INSERT INTO `SQLiteCartas` VALUES ('Darkbomb','c471','Spell','Warlock','Goblins Vs Gnomes','Common',NULL,'2',NULL,NULL,'Deal 3 damage',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Demonfire','c472','Spell','Warlock','Classic','Common',NULL,'2',NULL,NULL,'Deal 2 damage to a minion. If it''s a friendly Demon, give it +2/+2 instead',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Demonheart','c473','Spell','Warlock','Goblins Vs Gnomes','Epic',NULL,'5',NULL,NULL,'Deal 5 damage to a minion. If it''s a friendly Demon, give it +5/+5 instead',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Doomguard','c474','Minion','Warlock','Classic','Rare','Demon','5','5','7','Charge. Battlecry: Discard two random cards',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Drain Life','c475','Spell','Warlock','Basic','Basic',NULL,'3',NULL,NULL,'Deal 2 damage. Restore 2 health to your hero','2');
INSERT INTO `SQLiteCartas` VALUES ('Dread Infernal','c476','Minion','Warlock','Basic','Basic','Demon','6','6','6','Battlecry: Deal 1 damage to ALL other characters','2');
INSERT INTO `SQLiteCartas` VALUES ('Fel Cannon','c477','Minion','Warlock','Goblins Vs Gnomes','Rare','Mech','4','3','5','At the end of your turn, deal 2 damage to a non-Mech minion',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Felguard','c478','Minion','Warlock','Classic','Rare','Demon','3','3','5','Taunt. Battlecry: Destroy one of your Mana Crystals',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Flame Imp','c479','Minion','Warlock','Classic','Common','Demon','1','3','2','Battlecry: Deal 3 damage to your hero',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Floating Watcher','c480','Minion','Warlock','Goblins Vs Gnomes','Common','Demon','5','4','4','Whenever your hero takes damage on your turn, gain +2/+2',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Hellfire','c481','Spell','Warlock','Basic','Basic',NULL,'4',NULL,NULL,'Deal 3 damage to ALL characters','2');
INSERT INTO `SQLiteCartas` VALUES ('Imp-losion','c482','Spell','Warlock','Goblins Vs Gnomes','Rare',NULL,'4',NULL,NULL,'Deal 2-4 damage to a minion. Summon a 1/1 Imp for each damage dealt',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Lord Jaraxxus','c483','Minion','Warlock','Classic','Legendary','Demon','9','3','15','Battlecry: Destroy your hero and replace it with Lord Jaraxxus',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mal''Ganis','c484','Minion','Warlock','Goblins Vs Gnomes','Legendary','Demon','9','9','7','Your other Demons have +2/+2. Your hero is Inmune',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mistress of Pain','c485','Minion','Warlock','Goblins Vs Gnomes','Rare','Demon','2','1','4','Whenever this minion deals damage, restore that much Health to your hero.',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Mortal Coil','c486','Spell','Warlock','Basic','Basic',NULL,'1',NULL,NULL,'Deal 1 damage to a minion. If that kills it, draw a card','2');
INSERT INTO `SQLiteCartas` VALUES ('Pit Lord','c487','Minion','Warlock','Classic','Epic','Demon','4','5','6','Battlecry: Deal 5 damage to your hero',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Power Overwhelming','c488','Spell','Warlock','Classic','Common',NULL,'1',NULL,NULL,'Give a friendly minion +4/+4 until end of turn. Then, it dies. Horribly',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Sacrificial Pact','c489','Spell','Warlock','Basic','Basic',NULL,'0',NULL,NULL,'Destroy a minion. Restore 5 health to your hero','2');
INSERT INTO `SQLiteCartas` VALUES ('Sense Demons','c490','Spell','Warlock','Classic','Common',NULL,'3',NULL,NULL,'Put 2 random Demons from you deck into your hand',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Shadow Bolt','c491','Spell','Warlock','Basic','Basic',NULL,'3',NULL,NULL,'Deal 4 damage to a minion','2');
INSERT INTO `SQLiteCartas` VALUES ('Shadowflame','c492','Spell','Warlock','Classic','Rare',NULL,'4',NULL,NULL,'Destroy a friendly minion and deal its Attack damage to all enemy minions',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Siphon Soul','c493','Spell','Warlock','Classic','Rare',NULL,'6',NULL,NULL,'Destroy a minion. Restore 3 Health to your hero',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Soulfire','c494','Spell','Warlock','Basic','Basic',NULL,'1',NULL,NULL,'Deal 4 damage. Discard a random card','2');
INSERT INTO `SQLiteCartas` VALUES ('Succubus','c495','Minion','Warlock','Basic','Basic','Demon','2','4','3','Battlecry: Discard a random card','2');
INSERT INTO `SQLiteCartas` VALUES ('Summoning Portal','c496','Minion','Warlock','Classic','Common',NULL,'4','0','4','Your minions costs (2) less, but not less than (1)',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Twisting Nether','c497','Spell','Warlock','Classic','Epic',NULL,'8',NULL,NULL,'Destroy all minions',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Void Terror','c498','Minion','Warlock','Classic','Rare','Demon','3','3','3','Battlecry: Destroy the minions on either side of this minion and gain their Attack and Health',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Voidcaller','c499','Minion','Warlock','Naxxramas','Common','Demon','4','3','4','Deathrattle: Put a random Demon from your hand into the battlefield',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Voidwalker','c500','Minion','Warlock','Basic','Basic','Demon','1','1','3','Taunt','2');
INSERT INTO `SQLiteCartas` VALUES ('Arathi Weaponsmith','c501','Minion','Warrior','Classic','Common',NULL,'4','3','3','Battlecry: Equip a 2/2 weapon',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Arcanite Reaper','c502','Weapon','Warrior','Basic','Basic',NULL,'5','5','2',NULL,'2');
INSERT INTO `SQLiteCartas` VALUES ('Armorsmith','c503','Minion','Warrior','Classic','Rare',NULL,'2','1','4','Whenever a friendly minion takes damage, gain 1 armor',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Battle Rage','c504','Spell','Warrior','Classic','Common',NULL,'2',NULL,NULL,'Draw a card for each damaged friendly character',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Bouncing Blade','c505','Spell','Warrior','Goblins Vs Gnomes','Epic',NULL,'3',NULL,NULL,'Deal 1 damage to a random minion. Repeat until a minion dies',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Brawl','c506','Spell','Warrior','Classic','Epic',NULL,'5',NULL,NULL,'Destroy all minions except one. (chosen randomly)',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Charge','c507','Spell','Warrior','Basic','Basic',NULL,'3',NULL,NULL,'Give a friendly minion +2 Attack and Charge','2');
INSERT INTO `SQLiteCartas` VALUES ('Cleave','c508','Spell','Warrior','Basic','Basic',NULL,'2',NULL,NULL,'Deal 2 damage to two random enemy minions','2');
INSERT INTO `SQLiteCartas` VALUES ('Commanding Shout','c509','Spell','Warrior','Classic','Rare',NULL,'2',NULL,NULL,'Your minions can''t be reduced below 1 Health this turn. Draw a card',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Cruel Taskmaster','c510','Minion','Warrior','Classic','Common',NULL,'2','2','2','Battlecry: Deal 1 damage to a minion and give it +2 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Crush','c511','Spell','Warrior','Goblins Vs Gnomes','Epic',NULL,'7',NULL,NULL,'Destroy a minion. If you have a damaged minion, this costs (4) less',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Death''s Bite','c512','Weapon','Warrior','Naxxramas','Common',NULL,'4','4','2','Deathrattle: Deal 1 damage to all minions',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Execute','c513','Spell','Warrior','Basic','Basic',NULL,'1',NULL,NULL,'Destroy a damaged enemy minion','2');
INSERT INTO `SQLiteCartas` VALUES ('Fiery War Axe','c514','Weapon','Warrior','Basic','Basic',NULL,'2','3','2',NULL,'2');
INSERT INTO `SQLiteCartas` VALUES ('Frothing Berserker','c515','Minion','Warrior','Classic','Rare',NULL,'3','2','4','Whenever a minion takes damage, gain +1 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Gorehowl','c516','Weapon','Warrior','Classic','Epic',NULL,'7','7','1','Attacking a minion costs 1 Attack instead of 1 Durability',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Grommash Hellscream','c517','Minion','Warrior','Classic','Legendary',NULL,'8','4','9','Charge. Enrage: +6 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Heroic Strike','c518','Spell','Warrior','Basic','Basic',NULL,'2',NULL,NULL,'Give your hero +4 Attack this turn','2');
INSERT INTO `SQLiteCartas` VALUES ('Inner Rage','c519','Spell','Warrior','Classic','Common',NULL,'0',NULL,NULL,'Deal 1 damage to a minion and give it +2 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Iron Juggernaut','c520','Minion','Warrior','Goblins Vs Gnomes','Legendary','Mech','6','6','5','Shuffle a Mine into your opponent''s deck. When drawn, it explodes for 10 damage',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Kor''kron Elite','c521','Minion','Warrior','Basic','Basic',NULL,'4','4','3','Charge','2');
INSERT INTO `SQLiteCartas` VALUES ('Mortal Strike','c522','Spell','Warrior','Classic','Rare',NULL,'4',NULL,NULL,'Deal 4 damage. If you have 12 or less Health, deal 6 instead',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Ogre Warmaul','c523','Weapon','Warrior','Goblins Vs Gnomes','Common',NULL,'3','4','2','50% chance to attack the wrong enemy',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Rampage','c524','Spell','Warrior','Classic','Common',NULL,'2',NULL,NULL,'Give a damaged minion +3/+3',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Screwjank Clunker','c525','Minion','Warrior','Goblins Vs Gnomes','Rare','Mech','4','2','5','Battlecry: Give a friendly Mech +2/+2',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Shield Block','c526','Spell','Warrior','Basic','Basic',NULL,'3',NULL,NULL,'Gain 5 armor. Draw a card','2');
INSERT INTO `SQLiteCartas` VALUES ('Shield Slam','c527','Spell','Warrior','Classic','Epic',NULL,'1',NULL,NULL,'Deal 1 damage to a minion for each Armor you have',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Shieldmaiden','c528','Minion','Warrior','Goblins Vs Gnomes','Rare',NULL,'6','5','5','Battlecry: Gain 5 Armor',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Siege Engine','c529','Minion','Warrior','Goblins Vs Gnomes','Rare','Mech','5','5','5','Whenever you gain Armor, give this minion +1 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Slam','c530','Spell','Warrior','Classic','Common',NULL,'2',NULL,NULL,'Deal 2 damage to a minion. If it survives, draw a card',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Upgrade!','c531','Spell','Warrior','Classic','Rare',NULL,'1',NULL,NULL,'If you have a weapon, give it +1/+1. Otherwise equip a 1/3 weapon',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Warbot','c532','Minion','Warrior','Goblins Vs Gnomes','Common','Mech','1','1','3','Enrage: +1 Attack',NULL);
INSERT INTO `SQLiteCartas` VALUES ('Warsong Commander','c533','Minion','Warrior','Basic','Basic',NULL,'3','2','3','Whenever you summon a minion with 3 or less Attack, give it Charge','2');
INSERT INTO `SQLiteCartas` VALUES ('Whirlwind','c534','Spell','Warrior','Basic','Basic',NULL,'1',NULL,NULL,'Deal 1 damage to ALL minions','2');
COMMIT;
