package com.ListViewAdapter;

import com.example.hs_project.R;
import com.example.hs_project.R.layout;

import android.content.Context;
import android.graphics.Point;
import android.os.Build;
import android.view.Display;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.view.LayoutInflater;
import android.app.ActionBar.LayoutParams;
import android.app.Activity;

public class collectionAdapter extends BaseAdapter {
    private Context mContext;
    private Integer[] myCollection = { R.drawable.c1,
    		R.drawable.c2,
    		R.drawable.c3,
    		R.drawable.c4,
    		R.drawable.c5,
    		R.drawable.c6,
    		R.drawable.c7,
    		R.drawable.c8,
    		R.drawable.c9,
    		R.drawable.c10,
    		R.drawable.c11,
    		R.drawable.c12,
    		R.drawable.c13,
    		R.drawable.c14,
    		R.drawable.c15,
    		R.drawable.c16,
    		R.drawable.c17,
    		R.drawable.c18,
    		R.drawable.c19,
    		R.drawable.c20,
    		R.drawable.c21,
    		R.drawable.c22,
    		R.drawable.c23,
    		R.drawable.c24,
    		R.drawable.c25,
    		R.drawable.c26,
    		R.drawable.c27,
    		R.drawable.c28,
    		R.drawable.c29,
    		R.drawable.c30,
    		R.drawable.c31,
    		R.drawable.c32,
    		R.drawable.c33,
    		R.drawable.c34,
    		R.drawable.c35,
    		R.drawable.c36,
    		R.drawable.c37,
    		R.drawable.c38,
    		R.drawable.c39,
    		R.drawable.c40,
    		R.drawable.c41,
    		R.drawable.c42,
    		R.drawable.c43,
    		R.drawable.c44,
    		R.drawable.c45,
    		R.drawable.c46,
    		R.drawable.c47,
    		R.drawable.c48,
    		R.drawable.c49,
    		R.drawable.c50,
    		R.drawable.c51,
    		R.drawable.c52,
    		R.drawable.c53,
    		R.drawable.c54,
    		R.drawable.c55,
    		R.drawable.c56,
    		R.drawable.c57,
    		R.drawable.c58,
    		R.drawable.c59,
    		R.drawable.c60,
    		R.drawable.c61,
    		R.drawable.c62,
    		R.drawable.c63,
    		R.drawable.c64,
    		R.drawable.c65,
    		R.drawable.c66,
    		R.drawable.c67,
    		R.drawable.c68,
    		R.drawable.c69,
    		R.drawable.c70,
    		R.drawable.c71,
    		R.drawable.c72,
    		R.drawable.c73,
    		R.drawable.c74,
    		R.drawable.c75,
    		R.drawable.c76,
    		R.drawable.c77,
    		R.drawable.c78,
    		R.drawable.c79,
    		R.drawable.c80,
    		R.drawable.c81,
    		R.drawable.c82,
    		R.drawable.c83,
    		R.drawable.c84,
    		R.drawable.c85,
    		R.drawable.c86,
    		R.drawable.c87,
    		R.drawable.c88,
    		R.drawable.c89,
    		R.drawable.c90,
    		R.drawable.c91,
    		R.drawable.c92,
    		R.drawable.c93,
    		R.drawable.c94,
    		R.drawable.c95,
    		R.drawable.c96,
    		R.drawable.c97,
    		R.drawable.c98,
    		R.drawable.c99,
    		R.drawable.c100,
    		R.drawable.c101,
    		R.drawable.c102,
    		R.drawable.c103,
    		R.drawable.c104,
    		R.drawable.c105,
    		R.drawable.c106,
    		R.drawable.c107,
    		R.drawable.c108,
    		R.drawable.c109,
    		R.drawable.c110,
    		R.drawable.c111,
    		R.drawable.c112,
    		R.drawable.c113,
    		R.drawable.c114,
    		R.drawable.c115,
    		R.drawable.c116,
    		R.drawable.c117,
    		R.drawable.c118,
    		R.drawable.c119,
    		R.drawable.c120,
    		R.drawable.c121,
    		R.drawable.c122,
    		R.drawable.c123,
    		R.drawable.c124,
    		R.drawable.c125,
    		R.drawable.c126,
    		R.drawable.c127,
    		R.drawable.c128,
    		R.drawable.c129,
    		R.drawable.c130,
    		R.drawable.c131,
    		R.drawable.c132,
    		R.drawable.c133,
    		R.drawable.c134,
    		R.drawable.c135,
    		R.drawable.c136,
    		R.drawable.c137,
    		R.drawable.c138,
    		R.drawable.c139,
    		R.drawable.c140,
    		R.drawable.c141,
    		R.drawable.c142,
    		R.drawable.c143,
    		R.drawable.c144,
    		R.drawable.c145,
    		R.drawable.c146,
    		R.drawable.c147,
    		R.drawable.c148,
    		R.drawable.c149,
    		R.drawable.c150,
    		R.drawable.c151,
    		R.drawable.c152,
    		R.drawable.c153,
    		R.drawable.c154,
    		R.drawable.c155,
    		R.drawable.c156,
    		R.drawable.c157,
    		R.drawable.c158,
    		R.drawable.c159,
    		R.drawable.c160,
    		R.drawable.c161,
    		R.drawable.c162,
    		R.drawable.c163,
    		R.drawable.c164,
    		R.drawable.c165,
    		R.drawable.c166,
    		R.drawable.c167,
    		R.drawable.c168,
    		R.drawable.c169,
    		R.drawable.c170,
    		R.drawable.c171,
    		R.drawable.c172,
    		R.drawable.c173,
    		R.drawable.c174,
    		R.drawable.c175,
    		R.drawable.c176,
    		R.drawable.c177,
    		R.drawable.c178,
    		R.drawable.c179,
    		R.drawable.c180,
    		R.drawable.c181,
    		R.drawable.c182,
    		R.drawable.c183,
    		R.drawable.c184,
    		R.drawable.c185,
    		R.drawable.c186,
    		R.drawable.c187,
    		R.drawable.c188,
    		R.drawable.c189,
    		R.drawable.c190,
    		R.drawable.c191,
    		R.drawable.c192,
    		R.drawable.c193,
    		R.drawable.c194,
    		R.drawable.c195,
    		R.drawable.c196,
    		R.drawable.c197,
    		R.drawable.c198,
    		R.drawable.c199,
    		R.drawable.c200,
    		R.drawable.c201,
    		R.drawable.c202,
    		R.drawable.c203,
    		R.drawable.c204,
    		R.drawable.c205,
    		R.drawable.c206,
    		R.drawable.c207,
    		R.drawable.c208,
    		R.drawable.c209,
    		R.drawable.c210,
    		R.drawable.c211,
    		R.drawable.c212,
    		R.drawable.c213,
    		R.drawable.c214,
    		R.drawable.c215,
    		R.drawable.c216,
    		R.drawable.c217,
    		R.drawable.c218,
    		R.drawable.c219,
    		R.drawable.c220,
    		R.drawable.c221,
    		R.drawable.c222,
    		R.drawable.c223,
    		R.drawable.c224,
    		R.drawable.c225,
    		R.drawable.c226,
    		R.drawable.c227,
    		R.drawable.c228,
    		R.drawable.c229,
    		R.drawable.c230,
    		R.drawable.c231,
    		R.drawable.c232,
    		R.drawable.c233,
    		R.drawable.c234,
    		R.drawable.c235,
    		R.drawable.c236,
    		R.drawable.c237,
    		R.drawable.c238,
    		R.drawable.c239,
    		R.drawable.c240,
    		R.drawable.c241,
    		R.drawable.c242,
    		R.drawable.c243,
    		R.drawable.c244,
    		R.drawable.c245,
    		R.drawable.c246,
    		R.drawable.c247,
    		R.drawable.c248,
    		R.drawable.c249,
    		R.drawable.c250,
    		R.drawable.c251,
    		R.drawable.c252,
    		R.drawable.c253,
    		R.drawable.c254,
    		R.drawable.c255,
    		R.drawable.c256,
    		R.drawable.c257,
    		R.drawable.c258,
    		R.drawable.c259,
    		R.drawable.c260,
    		R.drawable.c261,
    		R.drawable.c262,
    		R.drawable.c263,
    		R.drawable.c264,
    		R.drawable.c265,
    		R.drawable.c266,
    		R.drawable.c267,
    		R.drawable.c268,
    		R.drawable.c269,
    		R.drawable.c270,
    		R.drawable.c271,
    		R.drawable.c272,
    		R.drawable.c273,
    		R.drawable.c274,
    		R.drawable.c275,
    		R.drawable.c276,
    		R.drawable.c277,
    		R.drawable.c278,
    		R.drawable.c279,
    		R.drawable.c280,
    		R.drawable.c281,
    		R.drawable.c282,
    		R.drawable.c283,
    		R.drawable.c284,
    		R.drawable.c285,
    		R.drawable.c286,
    		R.drawable.c287,
    		R.drawable.c288,
    		R.drawable.c289,
    		R.drawable.c290,
    		R.drawable.c291,
    		R.drawable.c292,
    		R.drawable.c293,
    		R.drawable.c294,
    		R.drawable.c295,
    		R.drawable.c296,
    		R.drawable.c297,
    		R.drawable.c298,
    		R.drawable.c299,
    		R.drawable.c300,
    		R.drawable.c301,
    		R.drawable.c302,
    		R.drawable.c303,
    		R.drawable.c304,
    		R.drawable.c305,
    		R.drawable.c306,
    		R.drawable.c307,
    		R.drawable.c308,
    		R.drawable.c309,
    		R.drawable.c310,
    		R.drawable.c311,
    		R.drawable.c312,
    		R.drawable.c313,
    		R.drawable.c314,
    		R.drawable.c315,
    		R.drawable.c316,
    		R.drawable.c317,
    		R.drawable.c318,
    		R.drawable.c319,
    		R.drawable.c320,
    		R.drawable.c321,
    		R.drawable.c322,
    		R.drawable.c323,
    		R.drawable.c324,
    		R.drawable.c325,
    		R.drawable.c326,
    		R.drawable.c327,
    		R.drawable.c328,
    		R.drawable.c329,
    		R.drawable.c330,
    		R.drawable.c331,
    		R.drawable.c332,
    		R.drawable.c333,
    		R.drawable.c334,
    		R.drawable.c335,
    		R.drawable.c336,
    		R.drawable.c337,
    		R.drawable.c338,
    		R.drawable.c339,
    		R.drawable.c340,
    		R.drawable.c341,
    		R.drawable.c342,
    		R.drawable.c343,
    		R.drawable.c344,
    		R.drawable.c345,
    		R.drawable.c346,
    		R.drawable.c347,
    		R.drawable.c348,
    		R.drawable.c349,
    		R.drawable.c350,
    		R.drawable.c351,
    		R.drawable.c352,
    		R.drawable.c353,
    		R.drawable.c354,
    		R.drawable.c355,
    		R.drawable.c356,
    		R.drawable.c357,
    		R.drawable.c358,
    		R.drawable.c359,
    		R.drawable.c360,
    		R.drawable.c361,
    		R.drawable.c362,
    		R.drawable.c363,
    		R.drawable.c364,
    		R.drawable.c365,
    		R.drawable.c366,
    		R.drawable.c367,
    		R.drawable.c368,
    		R.drawable.c369,
    		R.drawable.c370,
    		R.drawable.c371,
    		R.drawable.c372,
    		R.drawable.c373,
    		R.drawable.c374,
    		R.drawable.c375,
    		R.drawable.c376,
    		R.drawable.c377,
    		R.drawable.c378,
    		R.drawable.c379,
    		R.drawable.c380,
    		R.drawable.c381,
    		R.drawable.c382,
    		R.drawable.c383,
    		R.drawable.c384,
    		R.drawable.c385,
    		R.drawable.c386,
    		R.drawable.c387,
    		R.drawable.c388,
    		R.drawable.c389,
    		R.drawable.c390,
    		R.drawable.c391,
    		R.drawable.c392,
    		R.drawable.c393,
    		R.drawable.c394,
    		R.drawable.c395,
    		R.drawable.c396,
    		R.drawable.c397,
    		R.drawable.c398,
    		R.drawable.c399,
    		R.drawable.c400,
    		R.drawable.c401,
    		R.drawable.c402,
    		R.drawable.c403,
    		R.drawable.c404,
    		R.drawable.c405,
    		R.drawable.c406,
    		R.drawable.c407,
    		R.drawable.c408,
    		R.drawable.c409,
    		R.drawable.c410,
    		R.drawable.c411,
    		R.drawable.c412,
    		R.drawable.c413,
    		R.drawable.c414,
    		R.drawable.c415,
    		R.drawable.c416,
    		R.drawable.c417,
    		R.drawable.c418,
    		R.drawable.c419,
    		R.drawable.c420,
    		R.drawable.c421,
    		R.drawable.c422,
    		R.drawable.c423,
    		R.drawable.c424,
    		R.drawable.c425,
    		R.drawable.c426,
    		R.drawable.c427,
    		R.drawable.c428,
    		R.drawable.c429,
    		R.drawable.c430,
    		R.drawable.c431,
    		R.drawable.c432,
    		R.drawable.c433,
    		R.drawable.c434,
    		R.drawable.c435,
    		R.drawable.c436,
    		R.drawable.c437,
    		R.drawable.c438,
    		R.drawable.c439,
    		R.drawable.c440,
    		R.drawable.c441,
    		R.drawable.c442,
    		R.drawable.c443,
    		R.drawable.c444,
    		R.drawable.c445,
    		R.drawable.c446,
    		R.drawable.c447,
    		R.drawable.c448,
    		R.drawable.c449,
    		R.drawable.c450,
    		R.drawable.c451,
    		R.drawable.c452,
    		R.drawable.c453,
    		R.drawable.c454,
    		R.drawable.c455,
    		R.drawable.c456,
    		R.drawable.c457,
    		R.drawable.c458,
    		R.drawable.c459,
    		R.drawable.c460,
    		R.drawable.c461,
    		R.drawable.c462,
    		R.drawable.c463,
    		R.drawable.c464,
    		R.drawable.c465,
    		R.drawable.c466,
    		R.drawable.c467,
    		R.drawable.c468,
    		R.drawable.c469,
    		R.drawable.c470,
    		R.drawable.c471,
    		R.drawable.c472,
    		R.drawable.c473,
    		R.drawable.c474,
    		R.drawable.c475,
    		R.drawable.c476,
    		R.drawable.c477,
    		R.drawable.c478,
    		R.drawable.c479,
    		R.drawable.c480,
    		R.drawable.c481,
    		R.drawable.c482,
    		R.drawable.c483,
    		R.drawable.c484,
    		R.drawable.c485,
    		R.drawable.c486,
    		R.drawable.c487,
    		R.drawable.c488,
    		R.drawable.c489,
    		R.drawable.c490,
    		R.drawable.c491,
    		R.drawable.c492,
    		R.drawable.c493,
    		R.drawable.c494,
    		R.drawable.c495,
    		R.drawable.c496,
    		R.drawable.c497,
    		R.drawable.c498,
    		R.drawable.c499,
    		R.drawable.c500,
    		R.drawable.c501,
    		R.drawable.c502,
    		R.drawable.c503,
    		R.drawable.c504,
    		R.drawable.c505,
    		R.drawable.c506,
    		R.drawable.c507,
    		R.drawable.c508,
    		R.drawable.c509,
    		R.drawable.c510,
    		R.drawable.c511,
    		R.drawable.c512,
    		R.drawable.c513,
    		R.drawable.c514,
    		R.drawable.c515,
    		R.drawable.c516,
    		R.drawable.c517,
    		R.drawable.c518,
    		R.drawable.c519,
    		R.drawable.c520,
    		R.drawable.c521,
    		R.drawable.c522,
    		R.drawable.c523,
    		R.drawable.c524,
    		R.drawable.c525,
    		R.drawable.c526,
    		R.drawable.c527,
    		R.drawable.c528,
    		R.drawable.c529,
    		R.drawable.c530,
    		R.drawable.c531,
    		R.drawable.c532,
    		R.drawable.c533,
    		R.drawable.c534,
};
    private int copias = R.drawable.copia1;
    public collectionAdapter(Context c) {
        mContext = c;
    }
 
    public int getCount() {
        return myCollection.length;
    }
 
    public Object getItem(int position) {
        return null;
    }
 
    public long getItemId(int position) {
        return 0;
    }
 
    public View getView(int position, View convertView, ViewGroup parent) {
        GridHolder imageView;
        if (convertView == null) {
        	LayoutInflater inflater = ((Activity) mContext).getLayoutInflater();
        	convertView = inflater.inflate(layout.item_gridview, parent, false);
            imageView = new GridHolder();
            imageView.numItem = (ImageView) convertView.findViewById(R.id.item_text);
            imageView.imageItem = (ImageView) convertView.findViewById(R.id.item_image);
            Display display = ((Activity) mContext).getWindowManager().getDefaultDisplay();
            Point size = new Point();
            int alto;
            if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB_MR2){
            		display.getSize(size);
            			alto = size.y;
            }
            else {
            	alto = display.getHeight();
            }
            LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(LayoutParams.WRAP_CONTENT, alto/4);
            layoutParams.gravity = Gravity.CENTER;
            imageView.imageItem.setLayoutParams(layoutParams);
            layoutParams = new LinearLayout.LayoutParams(LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT);
            layoutParams.gravity = Gravity.CENTER;
            imageView.numItem.setLayoutParams(layoutParams);
            convertView.setTag(imageView);
        } else {
            imageView = (GridHolder)convertView.getTag();
        }

        imageView.imageItem.setImageResource(myCollection[position]);
        imageView.numItem.setImageResource(copias);
        return convertView;
    }
    
    static class GridHolder {
    	ImageView numItem;
    	ImageView imageItem; 
    }

}
